### ISSUE TITLE
Create command to clear Doctrine cache only

### ISSUE THREAD

**Issue by TNAJanssen** [snc/SncRedisBundle#119]
When we have an application running in production mode, we cache a lot through Redis including sessions. When we clear the cache because of a entity update (adding a field or renaming a field). We have the problem that if we don't clear Redis the new field isn't found by doctrine, and if we do clear the cache all sessions are gone.

**Comment by thvd** [comment]
:+1:

**Comment by AlmogBaku** [comment]
`bin/console doctrine:cache:clear-metadata`

**Comment by JHGitty** [comment]
Question answered. Please close this issue. :) #263

**Comment by JHGitty** [comment]
@Seldaek You have reopened this issue. What do you think is missing here? :)

**Comment by Seldaek** [comment]
Nothing, must have pressed twice by accident
