### ISSUE TITLE
Redis cannot be found

### ISSUE THREAD

**Issue by sparkeh9** [snc/SncRedisBundle#121]
After following installation instructions, I am getting the following in a symfony2 project...I don't have phpredis extension installed on my windows box

"Error: Class 'Redis' not found in ... app\cache\dev\appDevDebugProjectContainer.php line 673"

That line contains:
$this->services['doctrine.orm.default_redis_instance'] = $instance = new \Redis();

My composer.json contains:
        "predis/predis": "0.8.x-dev",
        "snc/redis-bundle": "1.1.*@dev",

config.yml contains
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %cache.redis.dsn%

Is there something I'm missing or forgetting to do?

Thanks!
Nick

**Comment by jcroll** [comment]
Did you install [phpredis](https://github.com/nicolasff/phpredis)?

**Comment by JHGitty** [comment]
I think this issue should be closed. This issue is just a question how to use this bundle and the issue is very old.
