### ISSUE TITLE
Memory leak somewhere in the bundle

### ISSUE THREAD

**Issue by Maxwell2022** [snc/SncRedisBundle#128]
I've used your bundle for a couple of hours and noticed a memory leak fetching hash in Redis.

I has a simple setup (default connection to `Redis` using `phpredis`) and around 100k hash in Redis.
The memory leak was occurring fetching hash `hGet()`

If you setup a loop with 100k fetch you'll see that the memory usage is growing rapidly.

I've stop using your bundle and use a simple connection using `phpredis` and now I can't see any memory issue. It's also much much faster !

Something must be wrong somewhere, maybe in your logging system.

**Comment by maxiloc** [comment]
Same here with the composer/packagist clone website. Every 3000 calls to redis via the package it's between 10 and 20 MB of leak. Calling directly Predis\Client works fine

**Comment by ProPheT777** [comment]
Same problem observed via https://github.com/GeniusesOfSymfony/WebSocketBundle.

* Monolog `finger_crossed` turned into stream
* Prod env

I'm using redis to store all client through websocket via SncRedis and after disconnect client I do not retrieve the initial memory.

I got approximately the same metrics as @maxiloc for 3000 calls between 10 and 20MB.

Without work fine.

**Comment by Imunhatep** [comment]
Any news?
