### ISSUE TITLE
Pretty big performance regression from 1.1.7 to 1.1.8

### ISSUE THREAD

**Issue by acasademont** [snc/SncRedisBundle#132]
Hi there,

We recently updated some of our project packages and redis-bundle was updated from 1.1.7 to 1.1.8. One week later I was checking or perfromance logs in newrelic (with a double-check with our in-house logstash/kibana) and there was a pretty big performance hit. After isolating that redis-bundle is the cause i've been reading throught the commit logs and it seems there is a new feature #120 session locking that now is enabled by default and that's the cause of the performance hit. 

![perf-redis-bundle](https://f.cloud.github.com/assets/825021/2528971/9e240290-b515-11e3-878c-e9c5aea81ad1.png)

As you can see (ignore the spike) median time went from ~60ms to ~72ms, that's a +20% increase in page load time, not negligible.

So my question here is: how the session locking thing is useful for us and why should we enable it?

Besides that, IMHO this feature should not have been enabled by default.

**Comment by ghanbari** [comment]
I have big problem by session, i think that its reason is session lock.
![image](https://cloud.githubusercontent.com/assets/3055667/20020441/861a221c-a2e6-11e6-8337-ee4d7fc2ed80.png)

bundle run very command for session set.

```
1	0.89 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
2	0.46 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
3	0.40 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
4	0.40 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
5	0.44 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
6	0.45 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
.
.
.
186	0.49 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
187	0.52 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
188	0.52 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
189	0.52 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
190	0.52 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
191	0.53 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
192	0.51 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
193	1.42 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
194	0.35 ms	default	GET session5m1vdrvau4jdmgiqu8300gqtq1
```

194 command for session set ;(

can i disable session lock? why we must use session lock?

**Comment by Seldaek** [comment]
See https://github.com/snc/SncRedisBundle/pull/403 and https://github.com/snc/SncRedisBundle/pull/404 to improve locking and reduce the need for it. But anyway closing this as it's easy to disable locking if you don't care for it:

```
snc_redis:
    clients:
        # ...
    session:
        client: session
        ttl: 3600
        locking: false
```
