### ISSUE TITLE
Doctrine ODM Caching

### ISSUE THREAD

**Issue by jamestooks** [snc/SncRedisBundle#142]
ODM caching doesn't seem to work.

Having investigated, it seems the problem lies with line 340 in SncRedisExtension.php.  The definition is being set to `doctrine.odm.mongodb.%s_%s` but it should be `doctrine_mongodb.odm.%s_%s`.

**Comment by dinhkhanh** [comment]
This issue seems still to exist. I have to make a hotfix in my local file.

**Comment by krzysztof-kabala** [comment]
> This issue seems still to exist. I have to make a hotfix in my local file.
confirmed, `Snc\RedisBundle\DependencyInjection\SncRedisExtension` line 341 should be replaced by:
`$container->setDefinition(sprintf('doctrine_mongodb.odm.%s_%s', $dm, $name), $def);`

current version doesnt work

**Comment by Nilz11** [comment]
This issue is still present in 2.0.0. Mongodb changed the naming already in 2012.

Note: line 304 doctrine is correct as it's the configuration of the SncRedisBundle
