### ISSUE TITLE
Circular reference "snc_redis.session" with Monolog Formatter, Processor

### ISSUE THREAD

**Issue by tobemedia** [snc/SncRedisBundle#161]
I try to customize the log entry and add some more information about the logged in user.
I use SncRedisBundle for the session handling, logging currently goes to file.

When adding a Monolog Formatter and Processor as told here:
http://symfony.com/doc/2.4/cookbook/logging/monolog.html
I get this error:
'Circular reference detected for service "snc_redis.session", path: "snc_redis.session"

**Comment by tobemedia** [comment]
PING
still the same...

**Comment by pculka** [comment]
PING in the same boat ...

**Comment by allauthors** [comment]
disable logging for the redis client which is used for sessions, then you will be able to inject session into your custom log processor without getting a circular reference.  
e.g.:
snc_redis:
    clients:
        session:
            type: predis
            alias: session
            dsn: redis://127.0.0.1
            logging: false
    session:
        client: session
        prefix: sess

**Comment by nathanlon** [comment]
Thanks, this worked for me.

**Comment by JHGitty** [comment]
Same issue here with the ``swiftmailer`` feature. I have opened #262.

**Comment by curry684** [comment]
I doubt that this is still relevant, retest appreciated.

**Comment by curry684** [comment]
Assuming this is indeed no longer an issue.
