### ISSUE TITLE
Configuration error "Invalid type for client options."

### ISSUE THREAD

**Issue by markkellyeire** [snc/SncRedisBundle#167]
Hey Guys,

I am currently trying to set up this bundle using a basic configuration:

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            logging: %kernel.debug%

I keep getting the following error message when try to access my client using:

$redis = $this->container->get('snc_redis.default');

Error message: 

throw new InvalidArgumentException("Invalid type for client options.");

I have been stuck on this for quite some time now and as it is at a very basic stage of the set up I feel it could be something simple. Any help with this would be much appreciated.

Thanks in advance

**Comment by JHGitty** [comment]
@markkellyeire Do you still get this issue? I think this issue should be closed because it is very old and should not occur anymore.
