### ISSUE TITLE
RedisSessionHandler needs to return true (for HHVM) 

### ISSUE THREAD

**Issue by karser** [snc/SncRedisBundle#168]
I encountered with this bug, that's true.
Here is the simmiliar discussion:
https://www.bountysource.com/issues/2853769-custom-sessionhandler-needs-to-return-true-for-hhvm

I use:
"snc/redis-bundle": "1.1.*@dev",
hhvm --version
HipHop VM 3.5.0-dev~nightly.2014.12.19 (rel)
Compiler: heads/master-0-g5c4ac76f5d3b2b4b972fd7db1d2580a4cc35ad50
Repo schema: 46c9b799c227a12b6c161fcbd528a745a927babc
Extension API: 20140829

**Comment by Sander-Toonen** [comment]
+1

I can confirm the issue above and the provided pull request does fix the it for me.

**Comment by curry684** [comment]
We're no longer providing support for HHVM following https://symfony.com/blog/symfony-4-end-of-hhvm-support
