### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ahmdmaher** [snc/SncRedisBundle#175]
i would like to know some information about the configuration 
1)what does alias means in the config?
What does secret@localhost mean? and if it is a user name where i can pass  the password (dsn: redis://secret@localhost/1)
What does profile 2.2 means? 
What is the usage of incr method? "$val = $redis->incr('foo:bar');"
Does the bundle support  redis  master-to-master replica?
Is there a way to disable redis cache in dev environment and test environment?

**Comment by scourgen** [comment]
1.alias means that you can use the second id of redis service
2.redis doesn't like mysql, there's no username, so secret@localhost which means that secret is the password.
more information please check http://redis.io/topics/security
3.you can imagine that is the version of your redis
4.add 1 on the value of key foo:bar 
5.It supports cluster
6.by using different config_xxx.yml file 


all your question are easy to get on web, please try to ask more valuable question next time.

**Comment by JHGitty** [comment]
All questions have been answered. :) Please close this issue. Related to #263
