### ISSUE TITLE
Can't save Redis 

### ISSUE THREAD

**Issue by skrobek** [snc/SncRedisBundle#176]
Hello,

i want to keep routing prettey urls in redis like: `pretty-url-value => actionName`. So after every update on record in db i have to save data for Redis. I'm using `Predis` client and i found that i can run raw command eg: `$client->executeRaw(['SAVE']);`

How can i execute raw command using this lib ? Or if there is a better way to do that ?

**Comment by JHGitty** [comment]
@skrobek Do you still have this issue? If not please close this issue.
