### ISSUE TITLE
PHP 5.6.7 Redis::scan() expected to be a reference

### ISSUE THREAD

**Issue by ddproxy** [snc/SncRedisBundle#178]
I'm getting the following error:

```
Warning: Parameter 1 to Redis::scan() expected to be a reference, value given
```

With the following code:

``` php
public function getCacheAction(Request $request, ParamFetcherInterface $paramFetcher)
{
    $redis = $this->container->get('snc_redis.data');
    $it = NULL; 
    $redis->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY); 
    while($arr_keys = $redis->scan($it)) {
        $array[] = $arr_keys;
    }
    return $array;
}
```

I'm using Symfony 2.6 and Redis Extension 2.2.7

I've narrowed down a possible cause of this issue.
#### Client\Phpredis\BaseClient

``` php
public function __call($name, array $arguments)
{
    if (null === $this->redis) {
        throw new \RuntimeException('You have to define a Redis instance before calling any command.');
    }

    return call_user_func_array(array($this->redis, $name), $arguments);
}
```

http://php.net/manual/en/function.call-user-func-array.php

> Note:
> Before PHP 5.4, referenced variables in param_arr are passed to the function by reference, regardless of whether the function expects the respective parameter to be passed by reference. This form of call-time pass by reference does not emit a deprecation notice, but it is nonetheless deprecated, and has been removed in PHP 5.4.

Without SncRedisBundle and using the Redis object directly,

``` php
$redis = new \Redis();
$redis->connect('127.0.0.1',6379);
$redis->select(2);
$it = NULL; /* Initialize our iterator to NULL */
$redis->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY); /* retry when we get no keys back */
$array = [];
while($arr_keys = $redis->scan($it)) {
    $array[] = $arr_keys;
}
return $array;
```

I get my expected return.

**Comment by luishdez** [comment]
Yep same problem

**Comment by ddproxy** [comment]
I'm not using scan anymore so I can't test of this is still an issue.

@luishdez - what version php, snc, and redis extension are you using?

**Comment by ddproxy** [comment]
I'm not using scan anymore so I can't test if this is still an issue.

@luishdez - what version php, snc, and redis extension are you using?

**Comment by romaincorral** [comment]
I'm the same problem with : 
- php 5.5.9-1ubuntu4.14
- redis 2.8.4
- phpredis 2.2.7
- snc/redis-bundle 1.1.x-dev

**Comment by luishdez** [comment]
@ddproxy Sorry I missed the comment I used all the next versions:

php 5.6.19 also tested with 7
redis  2.8 and 3.0.7 
phpredis 2.2.6 and 2.2.7
snc/redis-bundle  1.1.10 also tested with dev-master

**Comment by GeoffroyR** [comment]
If you still want to use snc (for the logs, connections,..) you can call the scan method trough call_user_func_array to pass the argument by reference:

`
// $redis = snc redis client
$iterator = null;
$arguments = array(&$iterator);
call_user_func_array(array($redis, 'scan'), $arguments));
`

**Comment by chteuchteu** [comment]
@GeoffroyR 's workaround doesn't work for me. Will this issue be fixed?

**Comment by feeela** [comment]
@snc This issue is still valid and open.

**Comment by abguy** [comment]
I have the same issue on PHP 7.0

**Comment by toooni** [comment]
@ddproxy @luishdez @romaincorral @GeoffroyR @chteuchteu @abguy this works now and can be closed!

**Comment by lightjiao** [comment]
I change `call_user_func_array` to [php splat](https://secure.php.net/manual/en/migration56.new-features.php)
```
public function __call($name, array $arguments)
{
    if (null === $this->redis) {
        throw new \RuntimeException('You have to define a Redis instance before calling any command.');
    }

    return $this->redis->$name(...$arguments);
}
```
