### ISSUE TITLE
Compatible with Twemproxy ?

### ISSUE THREAD

**Issue by ghisleouf** [snc/SncRedisBundle#179]
Hi all,

Is there someone who has already made this bundle work with Twemproxy ?
I'd like to get your feedbacks on it ... in case you have !

Thanks a lot !

**Comment by ShonM** [comment]
For anyone who stumbles on this, it's just a Redis client. It works with twemproxy as long as you don't call one of its unsupported commands.

**Comment by curry684** [comment]
See above.
