### ISSUE TITLE
Question about the Redis key

### ISSUE THREAD

**Issue by eexit** [snc/SncRedisBundle#181]
Hello,

I see you are adding a colon in the [Redis key format](https://github.com/snc/SncRedisBundle/blob/master/Session/Storage/Handler/RedisSessionHandler.php#L211) but I was wondering why not putting the colon in the [lock/unlock key](https://github.com/snc/SncRedisBundle/blob/master/Session/Storage/Handler/RedisSessionHandler.php#L111) as well?

Thanks,

**Comment by curry684** [comment]
Closing this issue in favor of #249 as it is more up to date and includes a patch  😉
