### ISSUE TITLE
30 seconds wasted in session locking

### ISSUE THREAD

**Issue by e7o-de** [snc/SncRedisBundle#182]
Hey,

having some issues with session locking. Figured out that #132 relates to this. My problem are such things in the logs (and, for sure, seeing the rendering time) before my actual code is running:

```
[2015-05-18 10:36:13] snc_redis.INFO: Executing command "SETNX sf9it65cploqnpr3ok88lo7iu8p5.loc[...] 1" [] []
[2015-05-18 10:36:13] snc_redis.INFO: Executing command "SETNX sf9it65cploqnpr3ok88lo7iu8p5.loc[...] 1" [] []
... 100 more of them ...
[2015-05-18 10:36:44] snc_redis.INFO: Executing command "SETNX sf9it65cploqnpr3ok88lo7iu8p5.loc[...] 1" [] []
[2015-05-18 10:36:44] snc_redis.INFO: Executing command "SETNX sf9it65cploqnpr3ok88lo7iu8p5.loc[...] 1" [] []
```

Stack trace is:

```
#0  Snc\RedisBundle\Logger\RedisLogger->logCommand() called at [/var/www/core/vendor/snc/redis-bundle/Snc/RedisBundle/Client/Predis/Connection/ConnectionWrapper.php:163]
#1  Snc\RedisBundle\Client\Predis\Connection\ConnectionWrapper->executeCommand() called at [/var/www/core/vendor/predis/predis/lib/Predis/Connection/PredisCluster.php:213]
#2  Predis\Connection\PredisCluster->executeCommand() called at [/var/www/core/vendor/predis/predis/lib/Predis/Client.php:246]
#3  Predis\Client->executeCommand() called at [/var/www/core/vendor/predis/predis/lib/Predis/Client.php:228]
#4  Predis\Client->__call()
#5  Predis\Client->setnx() called at [/var/www/core/vendor/snc/redis-bundle/Snc/RedisBundle/Session/Storage/Handler/RedisSessionHandler.php:111]
#6  Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler->lockSession() called at [/var/www/core/vendor/snc/redis-bundle/Snc/RedisBundle/Session/Storage/Handler/RedisSessionHandler.php:149]
#7  Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler->read() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php:69]
#8  Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy->read()
#9  session_start() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:148]
#10 Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:262]
#11 Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Session.php:89]
#12 Symfony\Component\HttpFoundation\Session\Session->get() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ContextListener.php:76]
#13 Symfony\Component\Security\Http\Firewall\ContextListener->handle() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php:69]
#14 Symfony\Component\Security\Http\Firewall->onKernelRequest()
#15 call_user_func() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61]
#16 Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
#17 call_user_func() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:164]
#18 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:53]
#19 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:170]
#20 Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() called at [/var/www/core/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:112]
#21 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() called at [/var/www/core/app/bootstrap.php.cache:2997]
#22 Symfony\Component\HttpKernel\HttpKernel->handleRaw() called at [/var/www/core/app/bootstrap.php.cache:2970]
#23 Symfony\Component\HttpKernel\HttpKernel->handle() called at [/var/www/core/app/bootstrap.php.cache:3119]
#24 Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle() called at [/var/www/core/app/bootstrap.php.cache:2368]
#25 Symfony\Component\HttpKernel\Kernel->handle() called at [/var/www/core/web/app.php:37]
```

Is there any way to stop this? Sure, I can disable the session locking, but I guess there must be a weird other reason for that. Anyone already stumbled over this?

Would be happy about some hints ;) Thx in advance!

Regards
Sven

**Comment by fantoine** [comment]
I also get this error from time to time.

I'm not really sure about what really happens but it seems like for some reasons the session is never unlocked, so the lock key is not deleted.
Then, the handler try as many attempts as possible (according to `max_execution_time`) to set the lock key which already exists.

**Comment by tristanbes** [comment]
I just got this after upgrading and found this issue.

php-fpm is killed because it's taking too much time (100+ line of `snc_redis.INFO: Executing command "SETNX yprox_sess_eblmo5esra5as73so21p8[...] 1" [] [`)

**Comment by Enleur** [comment]
@tristanbes you can disable spin-lock in parameters
```
snc_redis.session.locking: false
```

**Comment by Imunhatep** [comment]
Same here. v1.1.9

**Comment by The-Don-Himself** [comment]
@tristanbes for me disabling session locking renders my site unable to log in :(

**Comment by bakicdj** [comment]
Anoyone found the solution for this?

**Comment by snc** [comment]
The master branch contains new code for the session locking, see #230 and #236 (which I will merge later).

**Comment by tlaguz** [comment]
Bug still exists in v1.1.10

**Comment by bakicdj** [comment]
@tlaguz 1.1.7 works like charm

**Comment by aleksa2808** [comment]
Still not fixed, tried the 1.1.10 and 2.x-dev versions. The 1.1.7 one works only because there appears to be no locking whatsoever there.

For reference I am running a websocket server and a web server which are sharing the session via redis (predis v1.0). The websocket server grabs when the upgrade header is sent, but never releases it, so if I reload the page I have to wait 30 secs for the lock to expire.

**Comment by Pouix** [comment]
What version of PHP are you using? Which client? PhpRedis or Predis?
With PHP 7, I recommand you to use Predis because igbinary, compiled with PhpRedis, isn't released yet. See #259.

@aleksa2808 Session and PHP Websocket server is a real pain.
If you're only doing read-operations on the websocket-server side, locking isn't needed.

But if you really need it (write operations...), make sure the process open and close the session everytime. `RedisSessionHandler::close()` should be called.
You can do a simple check by monitoring Redis.

**Comment by aleksa2808** [comment]
@Pouix I was only writing to the session via the Http server, so I disabled locking. Tho I don't understand why this was happening, since the Websocket server reads from the session only during the initial "upgrade" header request and it should lock it up right after, yet it never did.

My issue is resolved for now, if I notice some race conditions with the sessions needing a locking mechanism, I'll look this up again.

**Comment by ghanbari** [comment]
I have big problem by session, i think that its reason is session lock.
![image](https://cloud.githubusercontent.com/assets/3055667/20020441/861a221c-a2e6-11e6-8337-ee4d7fc2ed80.png)

bundle run very command for session set.

```
1	0.89 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
2	0.46 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
3	0.40 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
4	0.40 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
5	0.44 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
6	0.45 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
.
.
.
186	0.49 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
187	0.52 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
188	0.52 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
189	0.52 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
190	0.52 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
191	0.53 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
192	0.51 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
193	1.42 ms	default	SET session5m1vdrvau4jdmgiqu8300gqtq1.lock 581ce28fabbf0 PX 30001 NX
194	0.35 ms	default	GET session5m1vdrvau4jdmgiqu8300gqtq1
```

194 command for session set ;(

I use php 5.6.16 and Predis client.
can i disable session lock? why we must use session lock?

**Comment by tlaguz** [comment]
When we disabled session lock, whole application crashed.
I suspect that symfony reads session at the beginning of the request and writes it back to cache at the end. You can have situation when two requests are processed:

```
| - request start/end

A: | ------------------------------ |
B:       | ------------- |
```

When request B changed sth in session then those changes would be overwritten by end of request A.

This is only my suspicion based on what was happening to our application. I may be wrong.

**Comment by gadelkareem** [comment]
This is still randomly happening. Is there any fix yet?

**Comment by mikemix** [comment]
Same problem here, wtf.

**Comment by ruslan-naryzhnyi** [comment]
Same problem here!
I just updated redis to latest 3.2.8 version, this solved the problem!

**Comment by Soullivaneuh** [comment]
@ruslan-naryzhnyi Not for me. I got the same issue.

Redis: 3.2.10
SncRedis: dev-master 86d8997

Configuration:

```yaml
snc_redis:
    clients:
        default:
            type: '%redis_client_type%'
            alias: default
            dsn: 'redis://%redis_host%'
            logging: '%kernel.debug%'
        session:
            type: '%redis_client_type%'
            alias: session
            dsn: 'redis://%redis_host%/1'
            logging: '%kernel.debug%'
        mailer:
            type: '%redis_client_type%'
            alias: mailer
            dsn: 'redis://%redis_host%/2'
            logging: '%kernel.debug%'
    session:
        client: session
        ttl: 3600
        locking: true
    swiftmailer:
        client: mailer
        key: '%redis_mailer_key%'
```

**Comment by curry684** [comment]
I've seen this happen a while ago still.

@jaztec you have any idea when we ran into this, and did we just remove the locking setting in the end?

**Comment by jaztec** [comment]
We actually were performing multiple heavy (+20s) async calls simultaneously. The "workaround" in our case was simply to queue the calls and then the problem no longer occurred.

So in the end we only had to fix our own design flaw :-)

**Comment by curry684** [comment]
Yeah well that still doesn't truly fix the underlying issue if it's still there, so the vote is still out on that one hehe.

@Soullivaneuh did you ever see it again since your last comment here?

**Comment by piotrkochan** [comment]
anyone, anything? this is still happening

**Comment by mikemix** [comment]
Either stop making multiple simultaneous calls or disable session locking.

**Comment by piotrkochan** [comment]
it is not even about simultaneous calls, lock does not disappears after 1 call

**Comment by piotrkochan** [comment]
Geez, I know why this is happens. I'm using "php" serializer. The lock invalidation script:
```
if redis.call("GET", KEYS[1]) == ARGV[1] then
                return redis.call("DEL", KEYS[1])
            else
                return redis.call("GET", KEYS[1])
            end
```

does not work because lock key contains:

`s:13:"5b1a6fcb744ef";`

instead of:

`5b1a6fcb744ef`

**Comment by piotrkochan** [comment]
#435

**Comment by stefanotauriello** [comment]
> @tristanbes you can disable spin-lock in parameters
> 
> ```
> snc_redis.session.locking: false
> ```

This fixed me!

**Comment by piotrkochan** [comment]
> > @tristanbes you can disable spin-lock in parameters
> > ```
> > snc_redis.session.locking: false
> > ```
> 
> This fixed me!

@stefanotauriello You really should enable session locking or at least think a little about it. Especially if you do some per-user parallel ajax requests which writes/reads a session.

Still, I don't know why this issue is open, #437 is merged.

**Comment by stefanotauriello** [comment]
> > > @tristanbes you can disable spin-lock in parameters
> > > ```
> > > snc_redis.session.locking: false
> > > ```
> > 
> > 
> > This fixed me!
> 
> @stefanotauriello You really should enable session locking or at least think a little about it. Especially if you do some per-user parallel ajax requests which writes/reads a session.
> 
> Still, I don't know why this issue is open, #437 is merged.

It happened me now on my local MacBook after several years. I don't know why it's happened but in that way i've fixed it

**Comment by B-Galati** [comment]
@piotrkochan Thanks, closing this issue as it is fixed.

**Comment by er1z** [comment]
Still occurrs. :(

**Comment by B-Galati** [comment]
@er1z Does it occur with 3.0.0-RC2 ?

**Comment by er1z** [comment]
Didn't check but I messed up with some combinations and as far as I found out: **never** use the same profile for session and anything else. Weird but worked.

**Comment by B-Galati** [comment]
@er1z Thx for the heads up!
