### ISSUE TITLE
Fatal error after update form 1.1.8 to 1.1.9

### ISSUE THREAD

**Issue by Cinal** [snc/SncRedisBundle#188]
Hi,

After update form 1.1.8 to 1.1.9 i get:

PHP Fatal error:  Class 'Predis\Profile\Factory' not found in /vendor/snc/redis-bundle/Snc/RedisBundle/DependencyInjection/SncRedisExtension.php on line 158

**Comment by snc** [comment]
You have to update your predis version constraint in your composer.json see https://github.com/snc/SncRedisBundle/pull/172#issuecomment-117118218.
