### ISSUE TITLE
JSON Encode Error Logging

### ISSUE THREAD

**Issue by austinh** [snc/SncRedisBundle#193]
JSON encoding failed: Malformed UTF-8 characters, possibly incorrectly encoded. Encoding: array (

I upgraded my symfony composer files lately, and got this error.

I have done a lot of research and its down to monolog. It's not a bug though, its a feature as of their latest release. They no longer suppress errors for UTF8 encoding on PHP 5.5 and up. 
It's coming from these files.

vendor/monolog/monolog/src/Monolog/Formatter/WildfireFormatter.php 
 NormalizerFormatter ->throwEncodeError (

Is there any way sncredisbundle can utf8_encode the log message?
The session is saved fine and everything else works, its purely the logging.

UPDATE: It's also possible that its because SNCRedis is adding an empty log command.

 RedisLogger ->logCommand ('', '0.081062316894531', 'session', false) 
a false command cannot be json_encode?

**Comment by JHGitty** [comment]
@austinh @Seldaek  Please close this issue because #616 has also been closed.

**Comment by JHGitty** [comment]
#263
