### ISSUE TITLE
Symfony 2.7 and recommended configuration for sessions, session.handler seems to be overwritten by Symfony2 default

### ISSUE THREAD

**Issue by rcousens** [snc/SncRedisBundle#196]
Hi,

Followed the setup instructions, but Redis was not used for sessions with Symfony 2.7.3 until I added the following lines to my config.yml:

```
framework:
    session:
        handler_id:  snc_redis.session.handler
```

Prior to changing this line, NativeSessionStorage was being used.I thought the FrameworkBundle might run after yours, but:

Line 413 from src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php

```
            $handlerId = $config['handler_id'];

            if ($config['metadata_update_threshold'] > 0) {
                $container->getDefinition('session.handler.write_check')->addArgument(new Reference($handlerId));
                $handlerId = 'session.handler.write_check';
            }

            $container->setAlias('session.handler', $handlerId);
```

Using Xdebug, the above ran first, then the SncRedisExtension.php->loadSession() did. It just didn't stick?

Can't explain it.

Maybe this helps someone else!

**Comment by rcousens** [comment]
Ok, I'm stupid. I was looking at SessionStorage not the proxied saveHandler.

So it was saving to Redis, for some reason I thought storage would go there too.

**Comment by rcousens** [comment]
Actually, I double checked.

I'm right, it's only using RedisSessionHandler as the handler when I change config.yml and specify the handler directly.

**Comment by Don87** [comment]
Close this, it is not an issue with the bundle but rather an issue with the documentation. My sessions werent working too until I searched a lot and found that those lines MUST be added for it to work. That is to say, they are part of the configuration, also read the Symfony doc about using Pdo as your session handler, it shows that the framework - sessions - config must be changed for it to work. This bundle is the same just that the docs do not say that.

**Comment by snc** [comment]
Was the `use_as_default` option set?
See https://github.com/snc/SncRedisBundle/blob/master/DependencyInjection/SncRedisExtension.php#L309-L311

**Comment by sekl** [comment]
I might have a similar issue. Symfony 2.7, "snc/redis-bundle": "1.1.x-dev", PHP 7, with both predis and phpredis.

This is my config:
```
session:
        handler_id:  snc_redis.session.handler
```

Although I've also tried 
```
session: ~
```

And for the bundle:
```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://xxx:1234
    session:
        client: default
        use_as_default: true
        ttl: 1200
```
Storing anything except sessions in Redis works fine, even Doctrine query/result cache works. However trying to store sessions in Redis results in:

> Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/session)

Looks like it's still trying the session handler/path set in the php.ini, instead of using snc_redis. 
Despite the error, checking redis reveals that it actually saves the anonymous session in redis:
> get session:jeinpe4ai2up2t4e8si5f05ct2
> $115
> _sf2_attributes|a:0:{}_sf2_flashes|a:0:{}_sf2_meta|a:3:{s:1:"u";i:1442543991;s:1:"c";i:1442542867;s:1:"l";s:1:"0";}

I'm really not sure if it's a problem with this bundle, my config, Symfony or our environment here. Any help appreciated.

**Comment by ruudk** [comment]
@sekl I have the exact same issue but on PHP7 RC4. Which version are you using?

**Comment by jimblizz** [comment]
I have the same issue trying to use sessions in Redis however I get no error message at all, it just acts as though the session does not exist.

PHP 5.6.14

**Comment by sekl** [comment]
@ruudk 7.0.0RC2 - still couldn't get it to work using this bundle but it's not urgent right now, so I'll see if it gets fixed at some point or else have to just do it without the bundle. Just wondering if I was doing something wrong. ;)

**Comment by a-sane** [comment]
@sekl @ruudk I have same on PHP7 RC3 and PHP7 RC4

**Comment by ruudk** [comment]
So where is this going wrong? In the Redis extension? In Symfony2? Or this bundle?

**Comment by a-sane** [comment]
@ruudk @sekl @jimblizz @rcousens  Guys, seems i found the problem. Problem in 1.1 branch in SncRedisBundle/Session/Storage/Handler/RedisSessionHandler.php. Write method in this class should return true.

```
    public function write($sessionId, $data)
    {
        if (0 < $this->ttl) {
            $this->redis->setex($this->getRedisKey($sessionId), $this->ttl, $data);
        } else {
            $this->redis->set($this->getRedisKey($sessionId), $data);
        }
        
        return true;
    }
```

 In master branch of SncRedis all is well

**Comment by ruudk** [comment]
It works! Thanks for helping me out @a-sane 

@snc Can you please create a new tagged release?

**Comment by sekl** [comment]
@a-sane This fixed my issue as well, thanks!

However, maybe the return should pass on the return value of the redis call.

```php
public function write($sessionId, $data)
{
    if (0 < $this->ttl) {
        return $this->redis->setex($this->getRedisKey($sessionId), $this->ttl, $data);
    } else {
        return $this->redis->set($this->getRedisKey($sessionId), $data);
    }
}
```

**Comment by blazarecki** [comment]
@a-sane Thanks for this fix.

**Comment by blazarecki** [comment]
Since there is no tag, you can use this in your `composer.json` : 

```
"snc/redis-bundle": "dev-master#bf7bbf0983b1e8c9a03ce2f9d5083939f756e882"
```

**Comment by snc** [comment]
There is now a tagged 1.1.10 release and the documentation was fixed in master (https://github.com/snc/SncRedisBundle/commit/06f7944f9472e5b605f642efda63db900f1a7307).
