### ISSUE TITLE
Problems with latest release

### ISSUE THREAD

**Issue by hugofcampos** [snc/SncRedisBundle#197]
What is the stable version of the Bundle? 

I followed the instructions and Composer installed version 1.1.9 (77f65e3d) in my project. But I'm currently getting an "Undefined index: alias" error. I saw that in master this problem was fixed, but this fixed isn't merged in the latest version loaded by Composer.

**Comment by snc** [comment]
1.1.9 is the latest version, can you link to the commit that fixed your problem?

**Comment by hugofcampos** [comment]
The commit trees of master and tag 1.1.9 are very different. I'm not sure what version I should use. In fact, 1.1.9 brings me the error mentioned above.

**Comment by JHGitty** [comment]
This issue is very old. I think @hugofcampos does not have this issue anymore because we are currently on version 1.1.10. Please close this issue. #263

**Comment by Seldaek** [comment]
2.0 is out now too
