### ISSUE TITLE
multiple app in one server

### ISSUE THREAD

**Issue by grekpg** [snc/SncRedisBundle#204]
If i have many apps in one server how i can setup it ?

snc_redis:
    clients:
        default:
            type: predis
            alias: app1_default
            dsn: redis://localhost
            logging: %kernel.debug%
        cache:
            type: predis
            alias: app1_cache
            dsn: redis://localhost/1
            logging: true
        cluster:
            type: predis
            alias: app1_cluster
            dsn:
                - redis://127.0.0.1/1
            options:
                profile: 2.4
                connection_timeout: 10
                connection_persistent: true
                read_write_timeout: 30
                iterable_multibulk: false
                throw_errors: true
                cluster: Snc\RedisBundle\Client\Predis\Connection\PredisCluster
                replication: false
    session:
        client: default
        prefix: app1_session
        use_as_default: true

and for other app2_ ?

if i do this i get error 

[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The service definition "snc_redis.default_client" does not exist.

**Comment by JHGitty** [comment]
Two solutions:

1. Use the same Redis instance for both Symfony projects. The first Symfony project must not use the same Redis databases as the second Symfony project.

2. Use an own Redis instance per Symfony project. You can have multiple Redis instances on the same server (on different ports).

#263

**Comment by curry684** [comment]
See above, the bundle supports both multiple connections and multiple Redis databases, it's up to the developer how to use them.
