### ISSUE TITLE
Deprecate RedisCache in favour to native Doctrine\Common\Cache\{RedisCache,PredisCache}

### ISSUE THREAD

**Issue by Koc** [snc/SncRedisBundle#205]
I think that there is no sense in this class because native support

https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RedisCache.php
https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/PredisCache.php

**Comment by tristanbes** [comment]
I'm :+1:

**Comment by Koc** [comment]
closed by #230
