### ISSUE TITLE
You can enable or disable SncRedisBundle dynamically?

### ISSUE THREAD

**Issue by Chrysweel** [snc/SncRedisBundle#206]
Hello.

I have a project, and this project is in two server. ( Server A and Server B )

In server A, I want save sessions in redis, but in Server B, I do not want to use SncRedisBundle.

There any possibility to disable SncRedisBundle without modify my AppKernel and config to Server B ?

Thanks in advance !

**Comment by snc** [comment]
No, if the bundle is loaded it requires valid configuration. You can achieve this by introducing a new environment for server B inheriting from your production environment and then load the bundle conditionally in your kernel.

**Comment by Chrysweel** [comment]
@snc Thanks for answering!

It is an option ! I'll try this solution . Thanks!

**Comment by Chrysweel** [comment]
I solve this problem. I dont know if the way correct, but it work:

In AppKernel.php
``` 
    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $yaml = new Parser();
        $parametersPath = $this->getRootDir().'/config/parameters.yml';
        $parameters = $yaml->parse(file_get_contents($parametersPath));

        $loader->load($this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml');

        if(isset($parameters['parameters']['redis_session']) && $parameters['parameters']['redis_session'] === true){
            $loader->load($this->getRootDir().'/config/redis_session.yml');
        }
    }
```

So only read config if in parameters I have parameter redis_session true.

I hope help other people with same problem ! :)
