### ISSUE TITLE
Create new tagged release

### ISSUE THREAD

**Issue by ruudk** [snc/SncRedisBundle#209]
See https://github.com/snc/SncRedisBundle/issues/196#issuecomment-151143425

Current master fixes a bug in PHP 7. Can you please create a new release?

**Comment by snc** [comment]
I'll try to find some time to tag a new release this week and have a look at all those other PRs and issues.

**Comment by csarrazi** [comment]
Hello @snc! Any news on this?

**Comment by snc** [comment]
No, sorry, the problem is that the 1.1 and master branch are not in sync, so I can't simply add a new tag.

**Comment by mehmetbilgin** [comment]
+1 for a new release.
We need below fix for our production server.
https://github.com/snc/SncRedisBundle/pull/126

**Comment by vlceklukas** [comment]
+1

**Comment by snc** [comment]
I've now updated the master branch and could need some testers ;-)

**Comment by Ninir** [comment]
@snc Did you get sufficient feedbacks? What can we help you with?

**Comment by rdohms** [comment]
anything else stooping the release of a tag?

**Comment by snc** [comment]
Yes, I think it is a good idea to remove compatibility with older symfony versions to simplify the code and maintenance.

**Comment by ruudk** [comment]
What about tagging current master as 1.1.20 and then start working on cleaning up ? Since current 1.1.19 does not work with PHP7 and some people are trying to upgrade. We are running master in production for a couple weeks now without problems.

**Comment by snc** [comment]
There are too many changes (https://github.com/snc/SncRedisBundle/compare/1.1...master) for a patch version I think. I never checked if all of them are BC.

**Comment by cs278** [comment]
@snc What about cherry picking bf7bbf0983b1e8c9a03ce2f9d5083939f756e882 into 1.1 and release that?

**Comment by xocasdashdash** [comment]
any news about this? https://github.com/snc/SncRedisBundle/commit/bf7bbf0983b1e8c9a03ce2f9d5083939f756e882 is pretty critical if you want to use redis to store Symfony sessions

**Comment by snc** [comment]
I've cherry-picked the commit and released it as 1.1.10.

**Comment by cs278** [comment]
:+1: Thanks @snc
