### ISSUE TITLE
Ignore "no connection" for localhost

### ISSUE THREAD

**Issue by JHGitty** [snc/SncRedisBundle#214]
Is there any way to ignore if there is no connection to a redis server on localhost dev setups?

```
ConnectionException in AbstractConnection.php line 168:
Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. [tcp://localhost:6379]
```

I want to run a local dev setup under Microsoft Windows without Redis but if the website is deployed it should be using Redis on the same machine. How to ignore it for the local setup?

**Comment by piotrkochan** [comment]
where is AbstractConnection.php file?

**Comment by JHGitty** [comment]
Duplicate issue, see #253.
