### ISSUE TITLE
Auth information from DSN read incorrectly

### ISSUE THREAD

**Issue by dzuelke** [snc/SncRedisBundle#218]
According to RFC 3986, a user info part without a password means that part is the user name, not a password.

Currently, the bundle does not accept `redis://irrelevant:realpass@host` as a DSN, and treats the "foobar" in `redis://foobar@host` as the password, which is in violation of the URI spec.

It should instead discard the "irrelevant" bit in the first example above and use "realpass" as the password.

In general, I recommend replacing the custom parser in `Snc\RedisBundle\DependencyInjection\Configuration\RedisDsn` with a combination of `parse_url()` and `parse_str()` (for the query part).

Also see https://tools.ietf.org/html/rfc3986#section-3.2.1 for more details.

**Comment by JHGitty** [comment]
:+1: Thanks. While I tried to find out how to use password within this bundle I was also confused about this. Let's fix it.

**Comment by Seldaek** [comment]
Fixed in `^2.0@dev` by https://github.com/snc/SncRedisBundle/pull/248
