### ISSUE TITLE
snc_redis must be configured

### ISSUE THREAD

**Issue by isbkch** [snc/SncRedisBundle#219]
I'm getting the following exception:
``` InvalidConfigurationException: The child node "clients" at path "snc_redis" must be configured. ```

I use Symfony 2.3 SncRedisBundle 1.1.x-dev

In config.yml I have
```snc_redis:
      clients:
          default:
              type: predis
              alias: default
              dsn: redis://localhost
              logging: %kernel.debug%
```
And I've followed the docs for installation... Any idea what would cause this ?

**Comment by echosa** [comment]
I had this issue. Turns out I had the `snc_redis` path configured under `parameters`, like this:

```
parameters:
    ... <other definitions>
    snc_redis:
        clients:
            default:
                ...
```

What I needed was `snc_redis` to be its own top-level path:

```
parameters:
    ... <other definitions>

snc_redis:
    clients:
        default:
            ...
```

In your given example, I don't see `snc_redis` at all. Do you have `clients` defined underneath `snc_redis`?

**Comment by JHGitty** [comment]
#263
