### ISSUE TITLE
Global DB select

### ISSUE THREAD

**Issue by Bordovsky** [snc/SncRedisBundle#220]
Hi, this is more like a question then an issue.
Is there way for selecting DB for all connection, using predis client?

I have in parameters.yml parameter, array of my redis servers (for load balance).
I am using all this servers, but I want select different database for each client.
When I am using one redis server it looks like this:

    clients:

        default:
            type: predis
            alias: default
            dsn: %redis_dsn%
            logging: false
            options:
                replication: true

        doctrine:
            type: predis
            alias: doctrine
            dsn: %redis_dsn%/1
            options:
                replication: true

But there is problem when 'redis_dsn' contains array. I would need something like this:

        doctrine:
            type: predis
            alias: doctrine
            dsn: %redis_dsn%
            select: 1
            options:
                replication: true

I hope it is clear what I want to achieve.

**Comment by Seldaek** [comment]
I think you'll have to run with duplicates dsns per client to achieve this, as it would require modifying the dsns to apply the select, might get tricky, and it's not possible right now.

If you'd like to work on a patch doing it I don't think it's impossible but not a very common feature I think so I'm closing the issue for now.

**Comment by Bordovsky** [comment]
I've made some "hot fix" for it for now. In parameters.yml I set database number for the client that has to have data aside of other clients data. In methods that are calling redis and this client I am doing firstly SELECT. 
It is not very nice solution but it does it's job.

I will think about the patch if I found more places to use this approach.
