### ISSUE TITLE
Phpiredis support

### ISSUE THREAD

**Issue by enleur** [snc/SncRedisBundle#221]
It would be great to have a [phpiredis](https://github.com/nrk/phpiredis) support out of the box.

You can override ConnectionFactory and use phpiredis adapters, but the ConnectionFactory class overrides only if logger is enabled.

**Comment by zaiddabaeen** [comment]
Has anything happened with this one? Is there a solution for using phpiredis with snc_redis?

I expected to find a connections configuration as in predis's documentation:

```php
$client = new Predis\Client('tcp://127.0.0.1', array(
    'connections' => array(
        'tcp'  => 'Predis\Connection\PhpiredisStreamConnection',
        'unix' => 'Predis\Connection\PhpiredisSocketConnection',
    ),
));
```

But the current configuration doesn't support changing the connection.

**Comment by snc** [comment]
I never used phpiredis, is the performance better than phpredis?

**Comment by enleur** [comment]
@zaiddabaeen you can override connection_factory
```
class ConnectionFactory extends BaseConnectionFactory
{
    public function __construct()
    {
        if (extension_loaded('phpiredis')) {
            $this->schemes = [
                'tcp' => 'Predis\Connection\PhpiredisStreamConnection',
                'unix' => 'Predis\Connection\PhpiredisStreamConnection',
                'redis' => 'Predis\Connection\PhpiredisStreamConnection',
                'http' => 'Predis\Connection\WebdisConnection',
            ];
        }
    }
}
```
in config.yaml
```
snc_redis:
    class:
        connection_factory: AppBundle\Predis\ConnectionFactory
```

@snc yes, it is. phpiredis uses C client for parsing/serialization

**Comment by zaiddabaeen** [comment]
Thanks @enleur I'll try it out.

@snc Check out this performance guide: https://github.com/nrk/predis/blob/master/FAQ.md#speaking-about-performances
