### ISSUE TITLE
Monolog RedisHandler with predis Client does'nt work.

### ISSUE THREAD

**Issue by Axxon** [snc/SncRedisBundle#222]
Hello everyone, i'm just starting this week to play with redis, i tried to post my logs into redis db but i think there is a mistake in the redisHandler at this section (l.68):

```
        $this->redis->multiExec(function($multi) use ($key, $buffer) {
            foreach ($buffer as $record) {
                $multi->rpush($key, $record);
            }
        });
```

The multiExec is supposed to be a command Id and the callable the attached argument for the createCommand method. But, when look into the redis documentation multiExec is'nt defined (edit. or that's a method removed into the predis Client).

So please, somebody more expert than me could fix that or explain me something that i missed.

So for a temporary solution i changed the function by:

```
            foreach ($buffer as $record) {
                $this->redis->rpush($key, $record);
            }
```

I think the callable had a performance reason to be, there probably a better solution.

**Comment by curry684** [comment]
Monolog handler has been removed in favor of native implementation.
