### ISSUE TITLE
support for symfony3

### ISSUE THREAD

**Issue by Ma27** [snc/SncRedisBundle#223]
symfony 3 was released some days ago, but I'd really appreciate seeing a new major release supporting symfony3 :)

**Comment by snc** [comment]
This is already in master branch but not yet tagged, would be nice if you could test it.

**Comment by Ma27** [comment]
thank you for your fast answer.
I have to wait until I'll do the major version bump to 3.x as there are other bundles that don't support 3.x. But when I do this, I can have a look at your code in dev-master.

**Comment by lashae** [comment]
@snc is there any schedule for tagging the Symfony3 compatible release?

**Comment by snc** [comment]
Would be nice to get some feedback before tagging.

**Comment by mustashio** [comment]
@snc I would like to help. What can I do? Are there any specific tests you want me to run? Do you want tests on a real-life application or clean installation?

**Comment by snc** [comment]
Any form of practical testing would help :+1:

**Comment by smedbergsimon** [comment]
+1

**Comment by sunra** [comment]
+1
stable version supporting Symfony 3 is needed
dev-master - has problems with Symfony Profiler

**Comment by snc** [comment]
@sunra what about opening a new issue describing the problem in detail or even providing a fix for it in a PR?

**Comment by lashae** [comment]
I'm running Symfony3 on PHP7. So far, I can verify the following:

- dev-master is installable via composer.
- I can get the `snc_redis.default` service on my controller.
- Incrementation via `snc_redis.default` service on a Redis index is successful.
- Doctrine metadata is successfully cached on Redis via `snc_redis.cache`.

**Comment by sunra** [comment]
@snc In fact, everything works well
I had not fully configured project

**Comment by spdionis** [comment]
Any idea when support for symfony 3 will be released?

**Comment by snc** [comment]
I'll try to do it this week.

**Comment by ssalat** [comment]
+1

**Comment by pdefreitas** [comment]
+1

**Comment by desarrolla2** [comment]
I have this from clean instalation of symfony3

  Problem 1
    - Installation request for snc/redis-bundle 1.1.x-dev -> satisfiable by snc/redis-bundle[1.1.x-dev].
    - Conclusion: remove symfony/symfony v3.0.1
    - Conclusion: don't install symfony/symfony v3.0.1
    - snc/redis-bundle 1.1.x-dev requires symfony/yaml >=2.1,<3.0 -> satisfiable by symfony/yaml[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.
1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, 
v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28
, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.
3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2
.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8,
 v2.8.0, v2.8.1].
    - don't install symfony/yaml v2.3.0|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.1|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.10|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.11|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.12|don't install symfony/symfony v3.0.1                                                                                   
    - don't install symfony/yaml v2.3.13|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.14|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.15|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.16|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.17|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.18|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.19|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.2|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.20|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.21|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.22|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.23|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.24|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.25|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.26|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.27|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.28|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.29|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.3|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.30|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.31|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.32|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.33|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.34|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.35|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.36|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.4|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.5|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.6|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.7|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.8|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.3.9|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.0|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.1|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.10|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.2|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.3|don't install symfony/symfony v3.0.1                                                                                    
    - don't install symfony/yaml v2.4.4|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.5|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.6|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.7|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.8|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.4.9|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.0|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.1|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.10|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.11|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.12|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.2|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.3|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.4|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.5|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.6|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.7|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.8|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.5.9|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.0|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.1|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.10|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.11|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.12|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.2|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.3|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.4|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.5|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.6|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.7|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.8|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.6.9|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.7.0|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.7.1|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.7.2|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.7.3|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.7.4|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.7.5|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.7.6|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.7.7|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.7.8|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.8.0|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.8.1|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.0|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.1|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.10|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.11|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.12|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.13|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.2|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.3|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.4|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.5|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.6|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.7|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.8|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.1.9|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.0|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.1|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.10|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.11|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.2|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.3|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.4|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.5|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.6|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.7|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.8|don't install symfony/symfony v3.0.1
    - don't install symfony/yaml v2.2.9|don't install symfony/symfony v3.0.1
    - Installation request for symfony/symfony == 3.0.1.0 -> satisfiable by symfony/symfony[v3.0.1].

**Comment by Ma27** [comment]
well since you didn't show us your composer.json I have no idea whether I'm right, but do try to load the snc/redis-bundle 1.x with sf3?
The current changes for sf3 support are unreleased in master, so you should include "snc/redis-bundle" on "dev-master".
But unless I've seen your composer.json I cannot really help you

**Comment by pdefreitas** [comment]
Dev-master is working fine. New release tagging is needed for those who are checking out stable.

**Comment by snc** [comment]
A new branch alias was added in #229.

**Comment by Ma27** [comment]
ping @snc how is it going with sf3 the release?

**Comment by andrewlakomski** [comment]
+1

**Comment by snc** [comment]
I just merged a bigger PR #230. Would be nice to get some feedback from somebody who uses session locking, doctrine caching and or phpredis (with logging).

**Comment by spdionis** [comment]
Is there some expected/guessed timeline for a stable release of 2.0?

**Comment by snc** [comment]
Unfortunately I got no feedback here how well the master branch works or not...

**Comment by sunra** [comment]
@snc 
snc/redis-bundle: dev-master 
works pretty well with Symfony 3.0.2

**Comment by nspyke** [comment]
@snc I've done some testing on the ~2.0@dev (commit baa89a36bdb2483d7571ba5a748f5bb9aa8a6b71)

Our setup is Symfony 2.8.2, Ubuntu 14.04, PHP 5.6.18. PHPRedis client, with logging in dev/test.
We're using this bundle for Doctrine caching (query and metadata) and Swiftmailer spooling, as well as general get/set values. I don't use this bundle for sessions.

I'm happy to report our unit tests and behat tests all pass issue free. Our behat tests cover 95% of our application. Manual testing also reveals no issues.

**Comment by marcemira** [comment]
@snc I'm on Symfony 3.0.3, using `dev-master`. I can confirm that session doesn't work. I'll try to find out more tomorrow

**Comment by ABM-Dan** [comment]
+1

**Comment by gjuric** [comment]
I believe that setting the session handler is needed for Symfony 2.8 as well.

I am just about to push the 2.0@dev to production, hopefully all goes well.

**Comment by sgasser** [comment]
Hi @gjuric.

Any news about version 2.0?

**Comment by gjuric** [comment]
Sorry, I am not the maintainer, but I can see how it could have been misinterpreted. 

What I meant is that I started using 2.0@dev branch on this bundle in production at my job :)

BTW, so far everything works as expected and I do not see a reason for not releasing this version. Since it is not a backwards compatible version, people should test their projects anyhow.

**Comment by suncat2000** [comment]
+1
Stable 2.0 version of this bundle with support of sf3 is needed!

**Comment by JHGitty** [comment]
SncRedis works fine here on Symfony 3.1.x-dev with SncRedis 2.x-dev.

**Comment by danger89** [comment]
If it works fine, rename the GitHub Project description (symfony2 --> Symfony).

**Comment by sgasser** [comment]
With master works find, but new release tagging is needed for those who are checking out stable.

**Comment by JHGitty** [comment]
@snc Please tag a new release! :+1:

**Comment by danger89** [comment]
Ps. Also fix the Travis build/docker images for version 2.*. :)

**Comment by Tarsonius** [comment]
@snc 2.0 stable release would be very nice! (y)

**Comment by Ma27** [comment]
closing this as the ``2.0`` release has been released...
