### ISSUE TITLE
Predis Client::multiExec no longer exists, but is still used in RateLimit

### ISSUE THREAD

**Issue by echosa** [snc/SncRedisBundle#228]
As you can see in the Predis changelog entry for v0.8.5 (2014-01-16):

> Predis\Client::multiExec(): superseded by Predis\Client::transaction() and to be removed in the next major release.

https://github.com/nrk/predis/blob/84060b9034d756b4d79641667d7f9efe1aeb8e04/CHANGELOG.md

However, the `multiExec` method is still used in the `RateLimit` class:

https://github.com/snc/SncRedisBundle/blob/6d513735ec0465013ec51b191e21894f057eb683/Extra/RateLimit.php#L35

https://github.com/snc/SncRedisBundle/search?utf8=✓&q=multiexec

I noticed this because I'm getting this error when trying to use `RateLimit`:

> Command 'MULTIEXEC' is not a registered Redis command. 

I assume this error is related to the non-existent function.

Potentially related to #222.

**Comment by Seldaek** [comment]
Fixed in master/2.x
