### ISSUE TITLE
Dependancy injection tagging of services

### ISSUE THREAD

**Issue by alister** [snc/SncRedisBundle#234]
It appears to be difficult to programmatically find out what services this bundle registers.  On the command line, a developer can dump the container and grep for 'snc_redis':

     app/console debug:container |grep snc_redis

I'd like to suggest adding a `$def->addTag('snc_redis.*tagname*');` to each instance (in `DependencyInjection/SncRedisExtension.php`) of `new Definition()`.

With this line, per `new Definition()` in place, and the tag names listed in the documentation, finding the services would be quite easy within a bundle's compile pass. See [Working with Tagged Services](http://symfony.com/doc/current/components/dependency_injection/tags.html).

**Comment by snc** [comment]
Interesting idea, what is your use case behind it?

**Comment by alister** [comment]
For myself, a bundle of tools, extending RedisBaseCommand that allows access to see what is in the various Redis DB caches. Primarily, its useful for debugging and investigating the use of Redis within an application.

For example, I'm going to be adding a swiftmailer spool, cached in Redis, and would like to easily dump the appropriately named snc_redis client - as well as seeing what other clients are available displayed by name rather than the more opaque number.

The hard part is deciding the naming and then documenting the existence of tags, the actual work in the code-base is just adding a setTag() to each Definition - and being consistent between the different client libraries available (predis/phpredis, etc).

**Comment by snc** [comment]
Closed, see #242.
