### ISSUE TITLE
PHP7 & session_write_close issue

### ISSUE THREAD

**Issue by Imunhatep** [snc/SncRedisBundle#237]
Version 1.1.9

Problem: Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp)

Though snc-redis configured and runs flawlessly on php5.6.
 
Resolution: http://stackoverflow.com/questions/34117651/php7-symfony-2-8-failed-to-write-session-data

in short: Redis session storage write method should return true, like in master branch.

**Comment by snc** [comment]
Fixed in 1.1.10.
