### ISSUE TITLE
Logging messages as INFO when they should be DEBUG

### ISSUE THREAD

**Issue by sonu27** [snc/SncRedisBundle#243]
The class is logging the messages as INFO, however they are quite verbose so I believe they should be marked as DEBUG.

Or certainly allow this to be configurable. I don't want this in my logs, but I need other INFO stuff being logged.

Another option would be to have it's own separate channel which can be excluded in monolog.

**Comment by snc** [comment]
If you don't want this in your logs, wouldn't it be simpler to just disable the logging for the clients?

**Comment by sonu27** [comment]
But I would like to see them when I put it in debug mode.
Why should I have to change my redis config too?

**Comment by curry684** [comment]
This request is being tracked in #329
