### ISSUE TITLE
Security tokens lost on mysql failure

### ISSUE THREAD

**Issue by 0xC0D3D00D** [snc/SncRedisBundle#246]
Hi there,

I have a problem storing sessions in redis. If for any reason we lose MySQL server and while the MySQL server is down a user sends a request to the server, His security token will be removed because the server cannot access mysql and it will be replaced with an empty token. Is there any way to prevent such incident?
It's important to me. Because we have a mobile game server and sometimes users even don't remember their username and lose their accounts and recovery process is hard.

**Comment by JHGitty** [comment]
Could you explain better how SncRedis is related to your issue?

**Comment by mdhheydari** [comment]
I reviewed SncRedis and it's okay, it seems that it's an issue in Symfony's security bundle.

**Comment by curry684** [comment]
Ok  😄
