### ISSUE TITLE
Backport to fix deprecation warning on 1.1 branch

### ISSUE THREAD

**Issue by czenker** [snc/SncRedisBundle#252]
When building the DI Container in Symfony 2.8 this deprecation is issued

> The Symfony\Component\DependencyInjection\Definition::setScope method is deprecated since version 2.8 and will be removed in 3.0.

This issue is already fixed with 6ee0e518f9420af06c5ef3360f0a99cccf5f39d9 on master, but would it be possible to also port this fix to 1.1? The fix is rather trivial and would not pose a BC break as `SCOPE_CONTAINER` is the default anyways.

**Comment by Ninir** [comment]
@snc Could you please set a new tag for this please? :-)

**Comment by bacbos** [comment]
+1, would be great to get a new tag for this to get rid of the deprecation warning in sf 2.8

**Comment by jcchavezs** [comment]
+1 Please do it. This can be a quick win.

**Comment by bacbos** [comment]
Bump

**Comment by curry684** [comment]
Should be fixed by now.
