### ISSUE TITLE
Invalid argument supplied for foreach() on Symfony/Bundle/FrameworkBundle/Console/Application.php:127

### ISSUE THREAD

**Issue by lewis-spears-flashtalking** [snc/SncRedisBundle#254]
When running unit tests, I receive the following error due to the $kernel->getBundles() & $kernel->hasParameter() method not being mocked.

Invalid argument supplied for foreach()

/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:127
/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:100
/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:538

**Comment by curry684** [comment]
The information supplied here does not indicate an issue in this bundle.
