### ISSUE TITLE
Problem with Predis\Profile\Factory

### ISSUE THREAD

**Issue by jorgeluisacostaalonso** [snc/SncRedisBundle#255]
I already install the bundle, I have a problem with the class ScnRedisExtension, its does not find the class Predis\Profile\Factory;
I dont found the class Predis\Profile\Factory in the directory

please someone can help me

**Comment by Pouix** [comment]
@jorgeluisacostaalonso I think you have an issue with dependencies.
How did you install SncRedisBundle? With Composer? Manually?

**Comment by jorgeluisacostaalonso** [comment]
I installed it with composer!! I did everything say in github SncRedis! i will reinstall the bundle agains, so I will let you know! thanks

**Comment by curry684** [comment]
Assuming this to be fixed by now.
