### ISSUE TITLE
Doctrine metadata cache, forms, type guesser.

### ISSUE THREAD

**Issue by PawelJi** [snc/SncRedisBundle#256]
After code review I have found that storing metadata in cache makes an error in recognition of entity manager(when using a few managers). Error appears when symfony form type gueser try to find out which entity manager to use, and each time only the default/first em is selected - as we can see in loadMetadata method, there is no info in cache  who is a parent em of given metadata. So in effect incorrect database is called.

Symfony 2.3, snc bundle ^1.1

**Comment by Pouix** [comment]
Have you tried the same test with another Cache? APC, Memcached...
Because when I read your issue, I think it comes from Doctrine ORM.

**Comment by PawelJi** [comment]
Maybe none one of given, but phpredis cache from doctrine so for has been tested with success(but of course is slower then predis, which is not supported).
Issue comes from create key process, in doctrine metadata has entity manager prefix, so collision is not possible.

**Comment by Pouix** [comment]
What's your Doctrine ORM version?

**Comment by curry684** [comment]
This is unlikely to (still) be an issue with this bundle.
