### ISSUE TITLE
Doctrine Redis Cache requires \Redis() not Predis\Client()

### ISSUE THREAD

**Issue by lewis-spears-flashtalking** [snc/SncRedisBundle#257]
I'm currently upgrading the SncRedisBundle to the latest version as part of my Symfony 2.8 upgrade. 

My code base is currently expecting a Symfony service for the **RedisCache** (previously _Snc\RedisBundle\Doctrine\Cache_ now _Doctrine\Common\Cache\RedisCache_).

The Doctrine\Common\Cache\RedisCache->**setRedis()** is now type hinted to use **\Redis** but the "snc_redis.default" service returns an instance of **Predis\Client**.

How can I get around this issue?

**Comment by Pouix** [comment]
@lewis-spears-flashtalking You need to use PredisCache `Doctrine\Common\Cache\PredisCache` along with Predis `Predis\Client`.

**Comment by arman-mukatov** [comment]
How you solved this problem?

**Comment by curry684** [comment]
As explained the Predis and PhpRedis implementations use different classes and therefore require different adapters.
