### ISSUE TITLE
Session handler 

### ISSUE THREAD

**Issue by wajaja** [snc/SncRedisBundle#260]
Hi; after you configure redisBundle for the storage of the session I get this message  **No connection could be made because the target computer has expressly refused.  [tcp://localhost:6379] **

here is my configuration:

    `snc_redis:`
    `clients:`
        `default:`
            `type:` `predis`
            `alias:` `default`
            `dsn:` `redis://localhost`
            `logging:` `%kernel.debug%`
        `cache:`
            `type:` `predis`
            `alias:` `cache`
            `dsn:` `redis://localhost:6379`
            `options:`
                `profile:` `2.2`
                `connection_timeout:` `10`
                `read_write_timeout:` `30`
        `session:`
            `type:` `predis`
            `alias:` `session`
            `dsn:` `redis://localhost/2`
        `cluster:`
            `type:` `predis`
            `alias:` `cluster`
            `dsn:`
                - `redis://localhost/3?weight=10`
                - `redis://localhost/4?weight=5`
                - `redis://localhost/5?weight=1`
    `session:`
        `client:` `session``

my host is:127.0.0.1  and my port is 80; 
please show me ; where is the probleme in my config

**Comment by JHGitty** [comment]
Is your redis server 100% running on ``localhost`` with port ``6379``?

**Comment by wajaja** [comment]
thank you for your reply; it is working now ; I had not run redis server.
but I have another problem. how do I cache my queries with doctrine and enter these requests in the controller? just one example
