### ISSUE TITLE
Logging not possible for session and swiftmailer

### ISSUE THREAD

**Issue by JHGitty** [snc/SncRedisBundle#262]
**Issues:**

```
[Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]
Circular reference detected for service "snc_redis.swiftmailer", path: "snc_redis.swiftmailer". 
```

```
[Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]
Circular reference detected for service "snc_redis.session", path: "snc_redis.session".
```

**Reason:**
You have been activated logging on the client that is used for the `session` or `swiftmailer` feature.

**Workaround:**
Disable logging for the client that is used for the `session` or `swiftmailer` feature.

**Please fix this issue or disallow logging on clients that are used for the `session` or `swiftmailer` feature.**

Related to #161.

**Comment by curry684** [comment]
I doubt that this is still relevant, retest appreciated.
