### ISSUE TITLE
Create service alias for each defined client

### ISSUE THREAD

**Issue by tiagobrito** [snc/SncRedisBundle#271]
In PHPStorm doesn't recognize the custom defined clients as a service, at least I always get missing service for my custom clients, except for the default one.

**Comment by alister** [comment]
I don't know what PHPStorm would be looking for to know what services exist, but as of v2.0, you can now at least find out some information about what services are set from the console command, in dev:

    $ bin/console debug:container --tag snc_redis.client

    Symfony Container Public Services Tagged with "snc_redis.client" Tag
    ====================================================================

     ------------------------- --------------- ----------------------------------------
      Service ID                alias           Class name
     ------------------------- --------------- ----------------------------------------
      snc_redis.admincache      admincache      Snc\RedisBundle\Client\Phpredis\Client
      snc_redis.cache           cache           Snc\RedisBundle\Client\Phpredis\Client
      snc_redis.default         default         Snc\RedisBundle\Client\Phpredis\Client
      snc_redis.session_cache   session_cache   Snc\RedisBundle\Client\Phpredis\Client
      ....

**Comment by curry684** [comment]
To my knowledge the current PhpStorm Symfony plugin handles this properly these days.
