### ISSUE TITLE
Consider creating project for session handler

### ISSUE THREAD

**Issue by patrickkusebauch** [snc/SncRedisBundle#273]
At this moment, session handler in this package is the only decent handler with session locking there is.
However to install it (and keep up with updates) via composer means I have to install the whole symfony framework bundle. That is a lot of "useless" files to autoload in every request. Can you please consider releasing the session handler as a separate package?

**Comment by snc** [comment]
It is possible to "skip" the installation of the dependencies via your `composer.json` if you define them in the `replace` section.

The following `composer.json` will only install this bundle:

``` json
{
    "name": "only-redis-bundle",
    "replace": {
        "symfony/framework-bundle": "3.0.0",
        "symfony/yaml": "3.0.0"
    },
    "require": {
        "snc/redis-bundle": "2.x-dev@dev"
    }
}
```

This will only add one PSR4 entry to the autoloader.

**Comment by phofmann-trust** [comment]
I tried getting rid of the stuff I don't need with "replace". Works fine without dev packages. But when I try to do a composer update with dev packages included, my composer takes up 100% cpu and never finishes. :(

I think a separate project for the session handler only would be great!

**Comment by curry684** [comment]
Given that we're now targetting Symfony 3.4+ with Flex and separate packages for all Symfony components this should not be an issue anymore.
