### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by mathroc** [snc/SncRedisBundle#278]
Symfony 3 has been released for a while now, is there any confirmed issue remaining that need to be taken care of before releasing a stable 2.0 ? (2.0 milestone is empty)

fwiw, we've been using ^2.0@dev for a few months without issues

**Comment by Seldaek** [comment]
I pinged snc to check if he had anything else planned, then if all is well I'll proceed with a release ASAP.

**Comment by Seldaek** [comment]
https://github.com/snc/SncRedisBundle/releases/tag/2.0.0

**Comment by mathroc** [comment]
thank you @Seldaek & @snc !
