### ISSUE TITLE
Redis AUTH support Colon (:) but SncRedisBundle doesn't.

### ISSUE THREAD

**Issue by JnMik** [snc/SncRedisBundle#282]
Had some kind of a headache when I discovered the bundle wasn't working in production because my sysadmin had setup some freaking complicated password ;)

Got it working for sure, but I guess this should be revised.

https://github.com/snc/SncRedisBundle/blob/2.0.0/DependencyInjection/Configuration/RedisDsn.php#L161

**Comment by snc** [comment]
Passwords in DSNs must now be properly urlencoded if they contain special characters, see https://github.com/snc/SncRedisBundle/releases/tag/2.0.0

**Comment by JnMik** [comment]
Oh right, ok I'll try that.
