### ISSUE TITLE
query_cache ignores DoctrineExtensions\Translatable query hint for fallback

### ISSUE THREAD

**Issue by martijnhartlief** [snc/SncRedisBundle#290]
When using 

`$query->setHint(
    \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
    'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
);`

in combination with

`$query->setHint(
    \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
    'en' // take locale from session or request etc.
);`

The query ignores the query hint and doesn't return the fallback language but the empty records.

**Comment by Pouix** [comment]
@martijnhartlief Have you added the hint for fallback after your two hints?
```php
// fallback
$query->setHint(
    \Gedmo\Translatable\TranslatableListener::HINT_FALLBACK,
    1 // will fallback to default locale translations instead of empty values if used. 0 for empty values.
);
```

**Comment by curry684** [comment]
This is not an issue with this bundle but with Doctrine ORM.
