### ISSUE TITLE
Using phpRedis for caching doctrine directly

### ISSUE THREAD

**Issue by dev-infobeans** [snc/SncRedisBundle#294]
Currently I am using phpredis with SncRedis bundle to implement caching. I am creating redis key-values on result. But now I want to cache doctrine queries directly from Repository. Please help me out how it will be possible.

Thanks in advance..

**Comment by curry684** [comment]
Based on your description I'm not sure I understand what you are trying to achieve and how. Given the age of the issue I'm assuming it's no longer relevant by now, and therefore I'll close the issue. Please open a new issue if you still have issues, providing a more detailed description of what your are trying to achieve and how.
