### ISSUE TITLE
Symfony connection redis cluster

### ISSUE THREAD

**Issue by outstaindig** [snc/SncRedisBundle#304]
Hello,
Symfony connection redis cluster encountered an error

Error is as follows
Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given

I use the third party bundle
     "snc/redis-bundle": "2.*",
     "predis/predis": "^1.0"

This is my configuration

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://192.168.74.132:6380
            logging: %kernel.debug%
        cache:
            type: predis
            alias: cache
            dsn: redis://192.168.74.132:6381
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30
        cluster:
            type: predis
            alias: cluster
            dsn:
                - redis://192.168.74.132:6380
                - redis://192.168.74.132:6381
                - redis://192.168.74.132:6382
                - redis://192.168.74.132:6383
                - redis://192.168.74.132:6384
                - redis://192.168.74.132:6385

it raises an exception in the predis client (predis/predis/src/Client.php:162):

I am eager to get help. In this first thank you

**Comment by Johny-it** [comment]
I'm experiencing the same issue and found out that snc's bundle sends "replication" => false in predis configuration (DependencyInjection/Configuration/Configuration.php:138)
But it seems that predis doesn't support replication:false parameter.
Predis documentation says that replication accepts only TRUE or callable object.
commenting out line 
->booleanNode('replication')->defaultFalse()->end()
in DependencyInjection/Configuration/Configuration.php
makes my case up and running.

**Comment by Johny-it** [comment]
Try to reduce version of predis bundle: 
change composer settings from:
"predis/predis": "^1.0"
to:
"predis/predis": "1.0.*"

predis 1.1 and 2.* don't support replication:false as a default value.

**Comment by outstaindig** [comment]
Thank you very much.I solved the problem of success.But a new error. 
Error message:
ERROR - Command "INCR foo:bar" failed (MOVED 9094 192.168.74.132:6381)
CRITICAL - Uncaught PHP Exception Predis\Response\ServerException: "MOVED 9094 192.168.74.132:6381" at /home/fujie/www/mySymfony/vendor/predis/predis/src/Client.php line 365 

I am study it.

**Comment by outstaindig** [comment]
My problem has been solved, is less a configuration.
    options:
                profile: 2.4
                connection_timeout: 10
                connection_persistent: true
                read_write_timeout: 30
                iterable_multibulk: false
                throw_errors: true
                cluster: redis-cluster
                replication: false

**Comment by curry684** [comment]
No longer an issue with current versions.
