### ISSUE TITLE
integration with platform.sh

### ISSUE THREAD

**Issue by bruno-ds** [snc/SncRedisBundle#314]
Hello,

I'm struggling with platform.sh limitation : first they "compile" the app (execute composer install) and then they "run" it. They don't provide the redis dsn during the "compile" time, so calls like `"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache"` or `Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets` in the composer.json file are making the compilation to crash.

Beside modifying the composer.json file, The only way to make things works seems to disable SncRedisBundle during this compilation process. Would it be possible?

Here is a link to a stackoverflow entry with more informations : http://stackoverflow.com/questions/41593312/using-sncredisbundle-on-platform-sh

**Comment by okwinza** [comment]
Disabling the bundle during container compilation aint going to help either.

There should be no calls to redis during that process at all.

**Comment by curry684** [comment]
This is a bug in platform.sh since the Composer scripts are allowed to assume the environment is properly up and running. platform.sh should install with `--no-scripts` option if they do a cold compile.
