### ISSUE TITLE
Doctrine ODM service name is still wrong

### ISSUE THREAD

**Issue by usmanzafar** [snc/SncRedisBundle#318]
Hey guys as per the ticket #143  this should have been fixed but turns out the latest version still miss these definitions. I was going through the history of the file and seems like as per this [commit](e461fb819b5b44481dda2a6ada60842922cefdb9) everything in reference to ODM definition reverted back without talking about why these are being reverted. 

I might be doing this wrong but can we revert that branch and merge it again, if not then i can send a quick PR if you guys cool with it ?

**Comment by snc** [comment]
Hi, a PR would be welcome.

**Comment by usmanzafar** [comment]
Aye aye captain, just sent a pr fingers crossed :). ps: I love this bundle this is my goto bundle for almost all projects. proud to be part of. cheers
