### ISSUE TITLE
PHPRedis RedisClient never throws and error

### ISSUE THREAD

**Issue by aurimasniekis** [snc/SncRedisBundle#323]
In `PHPRedis/Client::call` method line where is `logCommand` called has always static argument `$error = false`

https://github.com/snc/SncRedisBundle/blob/master/Client/Phpredis/Client.php#L66

**Comment by snc** [comment]
Waiting for your PR, maybe you could add a test for this, too :-)

**Comment by snc** [comment]
PR merged, thanks.

**Comment by aurimasniekis** [comment]
Fixed the code according comments #325
