### ISSUE TITLE
Feature Request: Compression

### ISSUE THREAD

**Issue by The-Don-Himself** [snc/SncRedisBundle#331]
I have been pondering the best place to request this, threads on redis discussions suggest within the app code to be the best place.

Compression of values can save at least 50% RAM in my Symfony app tests. Is this something SncRedisBundle can handle especially when Redis is used as a cache?

A see a few potential issues, though like if many App servers are connecting to a central Redis then they all must have the same compression library and version installed.

Thoughts?

**Comment by The-Don-Himself** [comment]
Just came across this PR that allows SncRedisBundle to explicitly select a serializer. Choosing [igbinary](https://github.com/igbinary/igbinary) might result in significant data compression savings about ~50% according to many benchmarks like this [drupal discussion](https://www.drupal.org/node/2143149).

https://github.com/snc/SncRedisBundle/pull/297

**Comment by dbergunder** [comment]
👍  This would be a great addition.

**Comment by pounard** [comment]
Using gzip may hold up to 80% memory saving, I implemented it in the Drupal Redis module. Until now, it never affected performance, but on many system hold a huge memory save.

**Comment by The-Don-Himself** [comment]
Seems to be solved by today's release v 2.1.1 by selecting Igbinary serializer, this PR by @yellow1912 adding this great option https://github.com/snc/SncRedisBundle/pull/411
Would have loved to see json_encode as a serializer option since it allows portability with other programming languages like GO while still improving memory savings.
