### ISSUE TITLE
Debugbar incorrectly reports errors

### ISSUE THREAD

**Issue by curry684** [snc/SncRedisBundle#334]
Resulting from commit https://github.com/snc/SncRedisBundle/commit/24503c77347b3eeab2c32512c8b133f8cb75d8e8, harmless `GET` operations on non-existent keys make the debug toolbar light up red with errors which are nowhere in logs or detail screen.

Imagine I run the command: `GET non_existent_key`. Per [the phpredis specs](https://github.com/phpredis/phpredis#get) this returns `false`, hence it is considered an error. As it isn't a real error `parent::getLastError()` returns `null`, which is then passed as `$error`.

The [logger itself](https://github.com/snc/SncRedisBundle/blob/master/Logger/RedisLogger.php#L54) just tests for `if ($error)`, so it doesn't log anything. The [Data Collector](https://github.com/snc/SncRedisBundle/blob/master/DataCollector/RedisDataCollector.php#L77) on the other hand does a typesafe test for `false`, so it does get counted, causing the red toolbar warning.

For those of us using the Doctrine metadata caches this problem occurs all the time as Doctrine frequently tests for key `DoctrineNamespaceCacheKey[]` which initially doesn't exist.

**Comment by curry684** [comment]
I'm afraid that commit will need to be reverted. Diving further into the phpredis docs I see many operations like `hget`, `rpop`, `setnx` etc. etc. return `false` for harmless and expected fails, which makes it impossible to generically discern them from `bgRewriteAOF`, `resetStat` and `script` where it implies a hard error.

It would appear the only solution is to give `call` a third argument `$checkErrors = false` and patch the command stubs that can fail hard to pass `true` for it.

**Comment by peteward** [comment]
👍 

Just had a scare of seeing 500+ 'errors' on my page when it's a harmless `GET` returning false.

**Comment by ragusa87** [comment]
I can confirm, debugbar reports errors, but you can't see them in the panel.
![tmp](https://cloud.githubusercontent.com/assets/1695207/26100968/c4a5dd92-3a2f-11e7-93f3-8678fbd5e7b4.png)
If I dump command.error, i can see that it can be `null` or `false`, and it's not handled in `getErroredCommandsCount`. See: https://github.com/snc/SncRedisBundle/blob/master/DataCollector/RedisDataCollector.php#L77

**Comment by yamilovs** [comment]
Same problem =)

**Comment by curry684** [comment]
This will need a thorough investigation on what use cases to tackle how. For instance when calling `get` there's a huge difference between the 3 possible outcomes:
 1. A string value if it was set with a scalar
 2. `false` if the value was not set
 3. An error if the value is of wrong type like hash

This shouldn't be changed lightly as it might cause BC breaks. In the short term I still think the commit mentioned should be reverted as it's *causing* BC breaks right now.

**Comment by snc** [comment]
I've just reverted #323 (and #325).

**Comment by curry684** [comment]
Thanks. Shouldn't we keep an issue open to track progress on what that PR was actually trying to solve and overshot?

**Comment by snc** [comment]
What are your thoughts on this @aurimasniekis?

**Comment by aurimasniekis** [comment]
I dont know fix the counting of errors or etc, my pull request just fixed the static false passed instead of error.
