### ISSUE TITLE
use SncRedisBundle, password is not in $options   when  new Predis\Client($parameters, $options);

### ISSUE THREAD

**Issue by mulandong** [snc/SncRedisBundle#336]
@nrk    @snc 
hello,I have a question

Predis Demo
``` php
$parameters = array('tcp://10.0.0.1, 'tcp://10.0.0.2', 'tcp://10.0.0.3');
$options = array('cluster' => 'redis','parameters' => array('password' => 'mypassword') );
$client = new Predis\Client($parameters, $options);
```
but when I use SncRedisBundle，password is not in $options, and error infomation "MOVED 12450 10.0.147.232"

how do I set password into $options? Thank you very much

**Comment by curry684** [comment]
Most likely fixed by #340, otherwise please open a new issue with current information.
