### ISSUE TITLE
`replication: sentinel` (currently on master branch) launches AUTH to sentinel instances

### ISSUE THREAD

**Issue by varas** [snc/SncRedisBundle#339]
This is a bug in the master brach since this merge https://github.com/snc/SncRedisBundle/commit/104df22b0391b69cef04ef69966d356ae76af0a4#diff-fd809ec659d77076dce28d9ea225b8f6L139

There is no way in config to distinguish between sentinel instances and redis ones. 

When trying  to connect to password protected redis instances I tried adding password via DSN, as it's the only way supported by the bundle.
https://github.com/snc/SncRedisBundle/blob/master/DependencyInjection/SncRedisExtension.php#L263-L264

So every time there is a password argument bundle converts password to an AUTH command, that is not supported by sentinel instances at the time: https://github.com/antirez/redis/issues/3279

Also: error is misleading as response command is not nicely handled by predis (see pic) and get masked as array access error.
![screen shot 2017-04-06 at 13 13 26](https://cloud.githubusercontent.com/assets/1300852/24757425/847a3fb6-1adf-11e7-9d66-c150c21a170b.png)

**Comment by snc** [comment]
@othillo can you have a look at this please (see #307)? I have never used sentinal, so you may have an idea about this issue.

**Comment by evgeny-s** [comment]
@othillo, also a question here: 
We moving to the sentinels architecture of our redis servers, and we use phpredis. 
As we expected, it should be something like this: 
1. We configure sentinels like this: host and port (26379 as default)
2. First client ask sentinel with request like ('GET-MASTER-ADD-BY-NAME') and then connect to the server with master role. I didn't find any reference to this command, seems now it works differently. Fix me if I mistaken.

Seems this is not possible to use phpredis for cluster connection.
Is it planned in the near future to add this feature?

Thank you very much.

**Comment by curry684** [comment]
I don't have access to Sentinel, can anyone confirm this was fixed properly by #340?

**Comment by varas** [comment]
I'm not longer working on this, but it seems to be solved at https://github.com/snc/SncRedisBundle/pull/340#issue-119084618

**Comment by curry684** [comment]
Thanks!
