### ISSUE TITLE
All values surrounded with s:number:"" after doctrine cache

### ISSUE THREAD

**Issue by Vandersteen** [snc/SncRedisBundle#343]
Is it expected behaviour to have every value surrounded with `s:[number]:\"[value]\"` once the doctrine cache has been hit ?

I'm running on php 7.1 with phpredis, symfony 2.8

Config:

    snc_redis:
        clients:
            default:
                type: phpredis
                alias: default
                dsn: %redis_dsn%
        doctrine:
            metadata_cache:
                client: default
                entity_manager: default
                document_manager: default
            result_cache:
                client: default
                entity_manager: [default]
            query_cache:
                client: default
                entity_manager: default
            second_level_cache:
                client: default
                entity_manager: default

Code to reproduce:

    $redis = $this->get('snc_redis.default');

    $redis->lPush('event', 'hmmm');

    $em->getRepository('AppBundle:Test');

    $redis->lPush('event', 'hmmm');

Example output:

    1495226032.394016 [0 127.0.0.1:55981] "LPUSH" "event" "hmmm"
    1495226037.652662 [0 127.0.0.1:56099] "GET" "DoctrineNamespaceCacheKey[]"
    1495226037.653147 [0 127.0.0.1:56099] "GET" [AppBundle\\Entity\\Test$CLASSMETADATA][1]"
    1495226037.664660 [0 127.0.0.1:56099] "LPUSH" "event" "s:4:\"hmmm\";"

**Comment by Vandersteen** [comment]
After fiddling around a bit more i managed to break it down to the following:

If the lPush happens after doctrine cache has been hit, the client starts to surround everything with the s::"".

In another script / request, if the rPop happens before the doctrine cache has been hit, the output will contain the s::"".

If the rPop happens after the doctrine cache has been hit, the s::"" is stripped away.

**Comment by snc** [comment]
This surroundings is the output of `serialize($value)`. It looks like doctrine enables the serializer for the client. So the solution/workaround to your problem is using multiple clients.

**Comment by curry684** [comment]
It's up to Doctrine to decide when to serialize or not, we're just the gateway in this so there isn't much we can do on our end.
