### ISSUE TITLE
Changing list of servers in runtime

### ISSUE THREAD

**Issue by oleg-andreyev** [snc/SncRedisBundle#346]
Right now we need to define (hardcode) all redis-nodes (or sentinel) in yaml and you cannot change it without cache recompilation, even with environment variables.

**Comment by kozlice** [comment]
This problem is outside bundle's scope. If your hosts IPs/ports are dynamic, you should use DNS service discovery (Consul, Docker's/Kubernetes' DNS, dnsmasq – depends on your environment).

**Comment by oleg-andreyev** [comment]
@kozlice it's not about a dynamic host, it's about environment variables, and afaik right now this bundle does not support env quite well.

**Comment by curry684** [comment]
But Symfony does: https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables

The default Symfony Flex recipe even does this explicitly, it defines a `REDIS_DSN` env variable in the `.env` file, and uses `dsn: '%env(REDIS_DSN)%` in the config.

This makes the issue indeed out of bundle scope as it's being handled well enough by Symfony.
