### ISSUE TITLE
Could you tag a new release?

### ISSUE THREAD

**Issue by ricbra** [snc/SncRedisBundle#347]
As there's quite some new stuff in master since last release. Maybe it would be nice to tag periodically? Every month or so? Most users don't want to rely on dev-master.

**Comment by Abam** [comment]
Yes, It would be greet to have a new tag. Especially for redis sentinel configuration support.

Any release scheduled ?

**Comment by Abam** [comment]
Ping @snc

**Comment by ricbra** [comment]
*crickets chirp*

**Comment by snc** [comment]
Done, thanks for your patience ;-)
