### ISSUE TITLE
What is sf2orm_****** in my database 0

### ISSUE THREAD

**Issue by CharlyPoppins** [snc/SncRedisBundle#354]
Hi,

I'm trying Redis with two differents apps, so I configure one **dsn** on **redis://localhost/1** and the other one on **redis://localhost/2**.

Then I still have some keys in ma database 0 :
```
 1) "sf2orm_toto_854ab9ccaaead01a46a74e2516630c8190d45614a98fef20932f9ef8131c4079[74745b840ffebd4963f1468f42d3dfbe][1]"
 2) "sf2orm_titi_62bc92310b7c2efe0f0784114343865a746253d1ce895561694501f38848e9dd[97772befd652aa4084f9224c886e5911][1]"
 3) "sf2orm_toto_854ab9ccaaead01a46a74e2516630c8190d45614a98fef20932f9ef8131c4079[b0427d4367346bf48117dab4de27a2f1][1]"
 4) "sf2orm_titi_854ab9ccaaead01a46a74e2516630c8190d45614a98fef20932f9ef8131c4079[68e39267767a22c16c8cab14d52f7348][1]"
 5) "sf2orm_toto_62bc92310b7c2efe0f0784114343865a746253d1ce895561694501f38848e9dd[27c737c04643b325b55437b918c1034a][1]"
 6) "sf2orm_titi_854ab9ccaaead01a46a74e2516630c8190d45614a98fef20932f9ef8131c4079[28fbce3d5530fd8c5e1dd62c5cf057dc][1]"
...
```

Where **toto** and **titi** are my **entity_managers**'s name (also my **dbname** name).

What are these keys ? How can I configure this so **toto** will be on **database 1** and **titi** in **database 2** ?

**Comment by CharlyPoppins** [comment]
up

**Comment by snc** [comment]
I guess this comes from doctrine... I don't know your config but maybe you have enabled some redis features from doctrine which don't rely on this bundle.

**Comment by curry684** [comment]
Assuming there is no longer an issue here.
