### ISSUE TITLE
After latest ppa:ondrej/php, SncRedisBundle stop working

### ISSUE THREAD

**Issue by Webonaute** [snc/SncRedisBundle#357]
our travis build script is using latest ppa from ppa:ondrej/php

and we started having this error message after yesterday ondrej update :

`[Symfony\Component\Debug\Exception\ContextErrorException]                                                         
  Warning: Declaration of Snc\RedisBundle\Client\Phpredis\Client::get() should be compatible with Redis::get($key)`

we are using the php 7.1 version with php-redis extension.

**Comment by vajiralasantha** [comment]
I have the same issue with one of my app. Have you found a solution for this?

**Comment by jonathanvanherpe** [comment]
We had the same issue, only fix so far is rolling back to 3.1.2 until SncRedisBundle adds a fix. the PPA doesn't offer the old version, so essentially you need to:

```
wget https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/12376483/+files/php-redis_3.1.2-1+deb.sury.org~xenial+1_amd64.deb
sudo dpkg -i php-redis_3.1.2-1+deb.sury.org~xenial+1_amd64.deb
```

until SncRedisBundle changes the way they call Redis::get($key)

Here's a related bug report in phpredis: https://github.com/phpredis/phpredis/issues/1233 , although people seem to be more focused on the fact that the developer introduced a breaking change in a minor version bump.

**Comment by vajiralasantha** [comment]
@jonathanvanherpe Thank you. Solved my issue for now.

**Comment by oerdnj** [comment]
The PPA has been downgraded to `3.1.2` again.

**Comment by andrja15** [comment]
I have latest ppa, but my version is 3.1.4. So PPA has been not downgraded to 3.1.2. 
I installed clean ubuntu 16.04 on vbox for test, and i got 3.1.4 version.

php -i |grep 'Redis Version'                                                                                                                                           
Redis Version => 3.1.4

apt-cache policy php-redis                                                                                                                                             
php-redis:
  Installed: 3.1.4-1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 3.1.4-1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 3.1.4-1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.7-389-g2887ad1+2.2.7-1 500
        500 http://ua.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

**Comment by oerdnj** [comment]
3.1.4 final has fixed the BC break.

**Comment by andrja15** [comment]
But i have the same problem, SncRedisBundle stop working. That's why i have asked about version.

**Comment by jekakm** [comment]
@oerdnj We still gets segfaults with latest redis extension from your repository.

**Comment by oerdnj** [comment]
And have you reported it to the upstream?

**Comment by andrja15** [comment]
http://dpaste.com/0VBVT25

**Comment by Kezino** [comment]
Same issue with version 4:
`[Symfony\Component\Debug\Exception\ContextErrorException] Warning: Declaration of Snc\RedisBundle\Client\Phpredis\Client::append() should be compatible with Redis::append($key, $value)`

**Comment by god1dog** [comment]
@Kezino i have version 4 and everything works

**Comment by netiul** [comment]
Having the same issue as @Kezino with version 4.0.0 of the php redis extension

**Comment by nick-zh** [comment]
same @netiul and @Kezino, also problems with redis ext 4.0.0

**Comment by curry684** [comment]
Issue with 4.0 is discussed at #399

**Comment by Seldaek** [comment]
Closing as 4.0.0 issues is tracked in #399 and 3.1.6 seems to work.
