### ISSUE TITLE
DSN with ENV Variables (Symfony 3.3.9). Request for release

### ISSUE THREAD

**Issue by juliolopeztorres** [snc/SncRedisBundle#360]
Hi there!

I'm trying to get my dsn information through env variables, i.e:

    snc_redis:
        clients:
            default:
                type: predis
                alias: default
                dsn: '%env(APP_REDIS_IP)%@%env(APP_REDIS_PORT)%'
                logging: %kernel.debug%

And I got literals as in issue #302. As I saw in #353, this problem has been solved and I can see these changes in master (https://github.com/snc/SncRedisBundle/tree/master/DependencyInjection/Configuration) but not in version tag 2.0.2 (https://github.com/snc/SncRedisBundle/tree/2.0.2/DependencyInjection).

Could you make a new tagged version including this fix so that composer can reach it @snc? 

Thank you!

**Comment by snc** [comment]
I've just tagged 2.0.3.

**Comment by juliolopeztorres** [comment]
Thank you!
