### ISSUE TITLE
Session fixation

### ISSUE THREAD

**Issue by pascal-hofmann** [snc/SncRedisBundle#364]
The session handler does not check if a session id is valid. It just silently creates a session for non-existent ids. This allows for session fixation attacks.

See also https://www.owasp.org/index.php/Session_fixation and http://php.net/manual/en/session.configuration.php#ini.session.use-strict-mode

**Comment by BboyKeen** [comment]
Does the PR https://github.com/snc/SncRedisBundle/pull/385 answers to your need ?

**Comment by pascal-hofmann** [comment]
I commented on your PR.

Short summary: Unfortunately not. :-(

**Comment by Seldaek** [comment]
See https://github.com/snc/SncRedisBundle/pull/404

**Comment by Seldaek** [comment]
Upcoming 3.0 will fix this.
