### ISSUE TITLE
how to Reset ttl ?

### ISSUE THREAD

**Issue by spectrelb** [snc/SncRedisBundle#368]
my config.yml ttl is 1440 ,but i need after login success , reset ttl 604800 , and logout reset ttl is 1440 , I added an event after login successfully, but it was unsuccessful 
please help me ( chinese: 我默认设置的是1440，但是我想在用户登录成功后，redis的ttl变成604800，退出时，又变成1400，我在登录成功后加了一个事件，但是不成功）

**Comment by charleslxh** [comment]
use session proxy!

**Comment by curry684** [comment]
The issue is unclear to me and therefore being closed to clean up the issue backlog. Please open a new issue if you still have questions or requests.
