### ISSUE TITLE
update for symfony 3.4+

### ISSUE THREAD

**Issue by cordoval** [snc/SncRedisBundle#372]
User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for class "Snc\RedisBundle\DataCollector\RedisDataCollector".

**Comment by xabbuh** [comment]
could probably be done as part of #370

**Comment by SiM07** [comment]
It's already fix in master. https://github.com/snc/SncRedisBundle/pull/366

**Comment by cordoval** [comment]
thanks @SiM07 you rock, do you mind giving us a tag? ✈️  taking off

**Comment by xabbuh** [comment]
Oh I should have remembered 🙈

**Comment by cordoval** [comment]
great work @xabbuh
