### ISSUE TITLE
Symfony 3.4/4.0 deprecations

### ISSUE THREAD

**Issue by COil** [snc/SncRedisBundle#374]
Hello,

There are several deprecations notices:

> User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for class "Snc\RedisBundle\DataCollector\RedisDataCollector".

I'll try to take a look when I have time.

See you.

**Comment by cordoval** [comment]
@COil close this, it already repeated and it is fixed or there is an open PR please

**Comment by COil** [comment]
Yes I just saw. Would be cool to release a new tag in this case.

**Comment by cordoval** [comment]
he will
