### ISSUE TITLE
Error in commit 58f8f3c with Symfony 2.8

### ISSUE THREAD

**Issue by luismatesanz** [snc/SncRedisBundle#375]
In the last commit there is an error with version Symfony 2.8.
The error is as follows:
 [InvalidArgumentException]                                                            
   The service "snc_redis.command.flush_all" tagged "console.command" must be public.

**Comment by snc** [comment]
Thanks for reporting! @romain-pierre was there a reason why you specified `public="false"` for them?

**Comment by romain-pierre** [comment]
Hi. Strange that this error have not been reported in tests...
This service definition is only used for sf4.

Probably you can just remove the tag, it will be **private in 4: good**, **public in 2.8: good** and **public in sf >= 3.1: not needed, should work**

**Comment by snc** [comment]
Fixed in 2.0.6.

**Comment by luismatesanz** [comment]
Thanks!
