### ISSUE TITLE
Clear cache failed on Symfony 2.7

### ISSUE THREAD

**Issue by ruiteix** [snc/SncRedisBundle#376]
Hi,

After upgrading to snc redis 2.0.5 symfony clear cache crash with this error :
`The service "snc_redis.command.flush_all" tagged "console.command" must be public`

I'am on symfony version 2.7.38.

Regards

**Comment by snc** [comment]
This is already fixed in 2.0.6.

**Comment by luismatesanz** [comment]
this is fixed up in issue #375

**Comment by ruiteix** [comment]
Thanks a lot !
