### ISSUE TITLE
Bundle is labelled as not-maintained as of 2016

### ISSUE THREAD

**Issue by lashae** [snc/SncRedisBundle#382]
On the [documentation index wiki page](https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md) bundle is label as not-maintained. 

![screen shot 2018-01-04 at 12 29 30](https://user-images.githubusercontent.com/20574/34557338-faeed476-f14a-11e7-8a98-0eb8297c20ee.png)

I suppose this is not correct as of 2018; if so, updating the so called wiki would be beneficial ;-)

**Comment by snc** [comment]
Thanks, fixed.
