### ISSUE TITLE
Predis vs Phpredis container definitions

### ISSUE THREAD

**Issue by LRotherfield** [snc/SncRedisBundle#383]
Is there a reason that a Predis client gets the [service definition](https://github.com/snc/SncRedisBundle/blob/master/DependencyInjection/SncRedisExtension.php#L205) name `snc_redis.CLIENT_ALIAS` but a Phpredis client gets the [service definition](https://github.com/snc/SncRedisBundle/blob/master/DependencyInjection/SncRedisExtension.php#L304) name `snc_redis.phpredis.CLIENT_ALIAS` and an alias to `snc_redis.CLIENT_ALIAS`

I only noticed because we have a couple of instances (using the oro platform, part of the cache dumping) where services are requested by `getDefinition` [method](https://github.com/symfony/dependency-injection/blob/master/ContainerBuilder.php#L967) rather than `findDefinition` [method](https://github.com/symfony/dependency-injection/blob/master/ContainerBuilder.php#L989) and so, when using the `snc_redis.CLIENT_ALIAS` key, Predis clients don't throw an error because they have an actual definition but Phpredis client definitions cannot be found as `getDefinition` does not look for aliases.

Would be interested to hear your thoughts

**Comment by curry684** [comment]
Agreed, pretty weird. Fixing it would imply major BC break though so let's see if we can get this done in 3.0.

**Comment by B-Galati** [comment]
Should be fixed in 3.0.0-RC1.
Please let me know.

**Comment by B-Galati** [comment]
Not fixed I will clean this up before stable (#452 )
