### ISSUE TITLE
Alias for services created via dependency injection are not public

### ISSUE THREAD

**Issue by sawmurai** [snc/SncRedisBundle#384]
First of all: Awesome bundle :)

When an alias is created here:

https://github.com/snc/SncRedisBundle/blob/2.0.6/DependencyInjection/SncRedisExtension.php#L206

it is created in a way that makes it private (it is private by default even if the service is public). By creating it like this

`
        $container->setAlias(sprintf('snc_redis.%s_client', $client['alias']), new Alias(sprintf('snc_redis.%s', $client['alias']), true));
`

it is possible to create it and make it public. 

Are the aliases supposed to be private or do you want a PR? :)

**Comment by sawmurai** [comment]
Hello there. Any thoughts about the one?

**Comment by xabbuh** [comment]
The best practice when using Symfony 3.4 or higher is to define almost all services private and rely on proper dependency injection instead of using the container as a service locator. So IMO not making them public is the desired behaviour.

**Comment by sawmurai** [comment]
I agree but this specific alias is for a service that is also declared public (a few lines above). So I think it would make sense to either declare the service private or declare the alias public to stay consistent.

**Comment by curry684** [comment]
We're preparing a 3.0 release targetting Symfony 3.4+ and PHP 7+ explicitly, currently in master branch. PR making it consistently private is breaking and therefore welcome if targeting master.

**Comment by curry684** [comment]
@sawmurai can you four-eye #409?

**Comment by sawmurai** [comment]
Looks good imo :)
