### ISSUE TITLE
Repo description is incorrect

### ISSUE THREAD

**Issue by rpkamp** [snc/SncRedisBundle#397]
The description of this repository is `A Redis bundle for Symfony2 supporting Predis and PhpRedis`, but it also works in Symfony 3 and 4. Might want to drop the 2 from the description.

**Comment by curry684** [comment]
@snc still need your powers for this one   😉

**Comment by snc** [comment]
Wow, this reminds me that I published the bundle back in 2010! Time to update the description 👍 
Thanks for the hint!
