### ISSUE TITLE
User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()"

### ISSUE THREAD

**Issue by Webonaute** [snc/SncRedisBundle#401]
User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Snc\RedisBundle\DataCollector\RedisDataCollector".

**Comment by xabbuh** [comment]
Looks like you need to update. This was fixed in #366 which was first released with 2.0.5.

**Comment by curry684** [comment]
See above.
