### ISSUE TITLE
Better handle the case when Redis is not installled

### ISSUE THREAD

**Issue by Nyholm** [snc/SncRedisBundle#406]
See original issue for details: https://github.com/symfony/recipes-contrib/issues/335#issuecomment-378136862

**Comment by curry684** [comment]
I'll pick this up, I was also looking into https://github.com/symfony/recipes-contrib/pull/339 for this reason.

**Comment by Nyholm** [comment]
Thank you

**Comment by curry684** [comment]
Closed by symfony/recipes-contrib#339 getting merged.
