### ISSUE TITLE
SncRedisBundle SwiftMailer integration needs SwiftMailer to be installed

### ISSUE THREAD

**Issue by PhilETaylor** [snc/SncRedisBundle#414]
Since https://github.com/snc/SncRedisBundle/commit/a26798998d7eeac85cfc241be812c7055df3ecdf

I get 

`SncRedisBundle SwiftMailer integration needs SwiftMailer to be installed`

if I try to use dev master with 

```
 "symfony/assetic-bundle": "^2.8",
    "symfony/dotenv": "^4.0",
    "symfony/monolog-bundle": "^3.2",
    "symfony/swiftmailer-bundle": "^3.2",
    "symfony/symfony": "3.4.*",
```

**Comment by curry684** [comment]
Oops, thanks and fixed!
