### ISSUE TITLE
Create a service locator for clients to be used in various locations

### ISSUE THREAD

**Issue by curry684** [snc/SncRedisBundle#419]
https://github.com/snc/SncRedisBundle/pull/409#issuecomment-382715587

Given that it's a change in `master` only we'll now have to ensure we have a service locator so the commands and other explicit usages still work.

**Comment by Basster** [comment]
@curry684 I've created #433, so the commands are working again. Feel free to point me to places where the service locator makes sense, too.

**Comment by curry684** [comment]
Sorry for my late reply, I've been swamped in work so haven't had a chance really to look at this yet. Right now we're maintaining 2.x and 3.x is "coming some day".

**Comment by B-Galati** [comment]
@curry684 I guess this one can be closed no? Should we add some docs about it?

**Comment by curry684** [comment]
Nah think it's fine like this, I kept it open mainly as a reminder to look at it once we'd cleaned up for 3.x but given the overall direction I don't see a reason to keep it around.

**Comment by B-Galati** [comment]
@curry684 Do you think we should document this feature or it should be marked as internal?
I guess it can be documented but I would like to have your thoughts :-)

**Comment by curry684** [comment]
As far as I'm concerned it's an implementation detail. If library consumers wish to use similar functionality they can and should use service subscribers instead.

**Comment by B-Galati** [comment]
Makes sense, agree! Thx!
