### ISSUE TITLE
How is with 3 version?

### ISSUE THREAD

**Issue by ambrous** [snc/SncRedisBundle#420]
Hi!

Could you please tell what is with 3 version of your great bundle?

We started to use 2.1.0 with symfony 3.4, and it worked well, but after updating to 2.1.1 our application started to load very long time and symfony profiler is being crashed with error that it is impossible to read session from /var/lib/php/session , although we use snc_redis.session.handler

Maybe just using version of ^2.0 is a very bad idea))

Thanks a lot!

**Comment by curry684** [comment]
The performance issue in 2.1.1 has been fixed already: https://github.com/snc/SncRedisBundle/releases/tag/2.1.2, see also #417 

Version 3 is in development and not likely to be released all too soon as we need to do some fundamental refactoring. The bundle hasn't been maintained much over the past 2 years or so meaning we have some catching up to do. 2.x should work fine though in all current applications, and you can use 3.0.x-dev if you really need the new session handler (just watch out with composer update).

> symfony profiler is being crashed with error that it is impossible to read session from /var/lib/php/session , although we use snc_redis.session.handler

We're not aware of any issues with the profiler, please open a dedicated issue to provide more details on this.
