### ISSUE TITLE
If Redis server is not reachable application returns 500 error

### ISSUE THREAD

**Issue by sgasser** [snc/SncRedisBundle#427]
We use this package since today for doctrine cache and we are tested several edge cases.

If the Redis server is not reachable we got a 500 error:
```
Connection refused [tcp://localhost:6379]
```

Should we make a PR to handle this?
If the "server" is not reachable we should only skip the cache so the app should continue normally.
What do you think?

**Comment by curry684** [comment]
This duplicates #253 and #105.

However you should keep in mind that Redis is not a cache, but an in memory key value store that just happens to be so damn fast it's often used as one. For tons of applications that use Redis for masterdata the behaviour you request is just as undesired as silently ignoring MySQL being down in others.

**Comment by sgasser** [comment]
Redis is not a cache. But if we use it only as doctrine cache, it makes no sense that the application got a 500 error if Redis is down. 

We will handle it in our fork.
