### ISSUE TITLE
PhpRedis DSN does not interpolate environment variables in 2.1.3

### ISSUE THREAD

**Issue by B-Galati** [snc/SncRedisBundle#428]
Details are in this comment https://github.com/snc/SncRedisBundle/pull/422#issuecomment-390840137 :

> I am not sure to understand the details of this PR, but I think it broke my setup (Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name does not resolve).
> 
> I debugged a bit: as parseDsn isn't executed anymore if an environment variable is detected, RedisDsn::getHost now returns null when called. However, in https://github.com/snc/SncRedisBundle/blob/master/DependencyInjection/SncRedisExtension.php#L294 the code calls it to generate the service definition during build, which leads to the following generated code:
> 
> 
> ```php
> use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
> 
> // This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
> // Returns the public 'snc_redis.session.handler' shared service.
> 
> $a = new \Snc\RedisBundle\Client\Phpredis\Client(array('alias' => 'default'), ($this->privates['snc_redis.logger'] ?? $this->getSncRedis_LoggerService()));
> $a->connect(NULL, 6379, 5);
> $a->setOption(1, 0);
> 
> return $this->services['snc_redis.session.handler'] = new \Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler($a, $this->parameters['session.storage.options'], 'session', true, 150000);
> ```
>
> As you can see, the client tries to connect to null as a host, which fails. I reverted for now (back to 2.1.2, which works) but I think this is a BC break. I am using the following configuration:
> 
>```yaml
> snc_redis:
>     clients:
>         default:
>             type: phpredis
>             alias: default
>             dsn: 'redis://%env(REDIS_HOST)%'
> 
>     session:
>         client: default
> ```
>
> I can try to create a reproducer but I don't think it should be difficult to create one using a basic Symfony 4 project as it's a container build issue.
> 
> Thanks for this great bundle and your work in open-source :) !
>

**Comment by fpondepeyre** [comment]
:+1: in the same boat...

**Comment by curry684** [comment]
I'm swamped in work before going on holiday next week so hoping someone else can dive into this...

**Comment by B-Galati** [comment]
I started working on a fix, it will be ready next week I think
