### ISSUE TITLE
symfony 4.0  "snc_redis.default" service or alias has been removed

### ISSUE THREAD

**Issue by jackyang1984** [snc/SncRedisBundle#430]
when i use $this->get("snc_redis.default")->hget($key, $field), error is display,

and in cache dir, public is false
<service id="snc_redis.default" class="Predis\Client" public="false">
      <tag name="snc_redis.client" alias="default"/>
      <argument type="service" id="snc_redis.connection.default_parameters.default"/>
      <argument type="service" id="snc_redis.client.default_options"/>
    </service>

snc_redis config is in /config/packages/framework.yaml

snc_redis:
    clients:
        default:
            type:             predis
            alias:            default
            logging:          '%kernel.debug%'
            dsn:              redis://localhost
        cache:
            type:             predis
            alias:            cache
            logging:          '%kernel.debug%'
            dsn:              redis://localhost
        profiler_storage:
            type:             predis
            alias:            profiler_storage
            logging:          '%kernel.debug%'
            dsn:              redis://localhost
        session:
            type:             predis
            alias:            session
            logging:          '%kernel.debug%'
            dsn:              redis://localhost
        monolog:
            type:             predis
            alias:            monolog
            logging:          false
            dsn:              redis://localhost

**Comment by curry684** [comment]
You are likely using AbstractController base class, which does not get the full container injected in Symfony 4. Either add `snc_redis.default` to the subscribed services or (better usually) inject the service via constructor injection.

**Comment by jackyang1984** [comment]
@curry684 i just use predis now

**Comment by curry684** [comment]
That doesn't matter really, Symfony changed it's way of exposing services in 4 to be more efficient and performant.

**Comment by jackyang1984** [comment]
@curry684 yes, Sy 4 is very like Java now, so i like it
