### ISSUE TITLE
lazyLoadingMethodInterceptor from proxy manager generates wrong Redis->set arguments part

### ISSUE THREAD

**Issue by boris-brtan** [snc/SncRedisBundle#443]
## What is happening
since the [commit](https://github.com/snc/SncRedisBundle/commit/2afed1dda117d6cc0572611badb5a267660783d4), there is  problem in the process of Doctrine fixtures load with generation of `Redis::set` method using `ProxyManager\ProxyGenerator\LazyLoadingValueHolder\MethodGenerator\LazyLoadingMethodInterceptor` where in the generated script Redis::set method contains 4 parameters instead of 3.

https://github.com/shopsys/shopsys/issues/336
```
In Redis_ca5fc0f.php line 1408:
[Symfony\Component\Debug\Exception\ContextErrorException]    
Warning: Redis::set() expects at most 3 parameters, 4 given
```

**Comment by curry684** [comment]
Duplicate #442
