### ISSUE TITLE
Connection via TLS (rediss) broken since 2.1.4

### ISSUE THREAD

**Issue by lucasvanlierop** [snc/SncRedisBundle#444]
v2.1.4 introduced a new way of parsing the dsn via `\Snc\RedisBundle\DependencyInjection\Configuration\RedisDsn`. It seems to discard the `rediss://` scheme which results in an dsn with the `tcp://` scheme rather than the expected `tls://` scheme. 

We (me and @jankramer) already took a quick look on fixing it by setting the scheme in the `RedisDsn` and retrieving it later on when building the dsn but we would first like to hear if you have a prefered way of fixing this. 

FYI: We are using the Predis client which, in contrary to PHPRedis, [supports TLS](https://github.com/nrk/predis/blob/6ab10b2b705ea5121f2c1ea87a290f6871c32ebd/tests/Predis/Connection/PhpiredisSocketConnectionTest.php#L42)

**Comment by B-Galati** [comment]
Thank you!

If the logic stays in the `parseUrl` method, it would be a good way of fixing it IMHO

**Comment by lucasvanlierop** [comment]
Fixed by #445
