### ISSUE TITLE
stable 3.x release

### ISSUE THREAD

**Issue by mathroc** [snc/SncRedisBundle#452]
Hi,

what's the status for the 3.x release ? any issues blocking the release ?

thank you

**Comment by curry684** [comment]
There's a few breaking things we'd like to fix: https://github.com/snc/SncRedisBundle/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0

Also the master branch currently does not contain the most recent improvements/fixes of 2.x and they're pretty complex to merge back. So we're not holding any schedule right now for 3.x going stable.

**Comment by B-Galati** [comment]
@curry684 Let me know if you need some help to merge 2.x in 3.x :+1:

**Comment by curry684** [comment]
I think it may just be a good idea to just throw out there what we have now as 3.0 asap, so at least we can drop support for outdated Symfony and PHP versions, and see from there what we want to do with 4.x regarding breaking stuff. Right now none of us have time to pick up all the big stuff and it'll just get messy to let the branches diverge even further.

So yes, if you can merge you last things back into 3 (you can see how far I've got, not much behind) I'm tempted to say we should just go beta with it.

**Comment by OskarStark** [comment]
any news here? A 3.0 would be great 👍

**Comment by curry684** [comment]
The merge attempt at #463 was kinda broken and I don't have time anywhere soon to fix it myself  😢

**Comment by B-Galati** [comment]
@curry684 Completely agree on this for a v4.

I'll try to merge v2 into v3 in coming weeks.

Any advices on what kind of manual tests I could do once done?

**Comment by curry684** [comment]
Not a clue, you haven't been around much shorter than I have hehe. Think it's mostly a matter of being 98% sure we did it right and throwing out a beta for people to try.

**Comment by OskarStark** [comment]
🎉 beta, beta, beta 🕺

**Comment by B-Galati** [comment]
RC1 is here :tada: 

https://github.com/snc/SncRedisBundle/releases/tag/3.0.0-RC1

Let me know for anything!

**Comment by OskarStark** [comment]
Any chance to get RC2 or stable? 🤗

**Comment by B-Galati** [comment]
I tagged RC2 few minutes ago as well as 2.1.9 :-)
I think we gonna release the v3 stable soon enough.

**Comment by curry684** [comment]
Just added RC2 to my main dev project for practical testing   :)

**Comment by OskarStark** [comment]
Many thanks 🙏

**Comment by kick-the-bucket** [comment]
Any news on an actual stable release? Or is the RC2 good enough for production as it is?

**Comment by B-Galati** [comment]
Thanks, RC2 could be good to go I think but we have some pending PRs #454 #511 that we would need to have in V3 and that would need a stabilization phase.

I am running out of time these days sadly.

**Comment by curry684** [comment]
I've been running RC2 without issues. Same issues with time   😾  hopefully some time to catch up with stuff during summer holidays.

**Comment by curry684** [comment]
@B-Galati @snc @Seldaek shouldn't we just release RC2 as 3.0 and see if we ever get those PRs and other pending stuff done for 4.0 when Symfony 5 comes?

**Comment by B-Galati** [comment]
I am ok with that!

Pending PRs could even be part of 3.1 version with an exceptional RC phase for stabilization.

We also have some few fixes on master that are not on RC2, what should we do with them? Released as part of 3.0 or RC3? They are minor fixes so I would say 3.0 could be fine.

**Comment by curry684** [comment]
Looking at https://github.com/snc/SncRedisBundle/compare/3.0.0-RC2...master I don't think any of them are really dangerous. I say we go 3.0.0 and have a 3.0.1 if stuff borks instead indeed.

**Comment by furester** [comment]
About PR #454 if I could do anything, please, let me know.

**Comment by B-Galati** [comment]
Released! -> https://github.com/snc/SncRedisBundle/releases/tag/3.0.0
