### ISSUE TITLE
PhpRedis Cluster

### ISSUE THREAD

**Issue by furester** [snc/SncRedisBundle#453]
Since there is no client implementing RedisCluster or RedisArray from PhpRedis is it possible (and how) to configure a cluster with this library instead of predis?

**Comment by curry684** [comment]
There is currently no support whatsoever on our end for `RedisCluster` and `RedisArray`.

**Comment by furester** [comment]
ok, thanks, i can try to manage `RedisCluster` support, 'cause I'm actually using it with old silex projects. I'll send a `pull request` then.

**Comment by furester** [comment]
i'll implement a common interface in `Client\Phpredis` to let developers switch between `\Redis` and `\RedisCluster` using only configuration files, but here it came first problem: these classes has methods with same name (`info` for example), but different footprint (`\Redis` and `\RedisCluster` doesn't implement a common interface - ref. https://github.com/phpredis/phpredis/issues/1298).

In the first implementation i'll comment out these methods to avoid conflicts, is it suitable for you?
