### ISSUE TITLE
Enable support for TLS connections (predis)

### ISSUE THREAD

**Issue by mvehar** [snc/SncRedisBundle#457]

**Comment by curry684** [comment]
Does Predis even support it?

Also - doesn't it more or less defeat the entire purpose of having the fastest in-memory key-value store on earth if you're then going to waste time setting up a TLS connection to it on every request? I'm all for the generic concept of "encrypt everything" but I've always considered Redis the single exception to it, and instead lock it down by (implicit) network security instead.

**Comment by mvehar** [comment]
On 2.1 branch (https://github.com/snc/SncRedisBundle/blob/2.1/DependencyInjection/Configuration/RedisDsn.php) is support already implemented. Pull request to update master branch is in progress.

**Comment by B-Galati** [comment]
This feature is supported on 2.1 and 3.0.0 to be released.
Thus I am closing this issue.
Let me know if I missed something.
See #445 .
