### ISSUE TITLE
snc_redis.doctrine_cache_predis configured to return PredisCache.php

### ISSUE THREAD

**Issue by BucGeo** [snc/SncRedisBundle#458]
snc_redis.doctrine_cache_predis configured to return PredisCache.php, a class with no public methods and no way of clearing cached Doctrine values.

**Comment by curry684** [comment]
What is the exact problem you are experiencing?

**Comment by BucGeo** [comment]
I've defined the doctrine portion of my sncRedis configuration:

`snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%redis_server%
    doctrine:
        result_cache:
            client: default
            entity_manager: [default]`

I have a listener set up to purge specific values from the cache by retrieving the related cache from the entity manager:

`$em->getConfiguration()->getResultCacheImpl()`

Because of this line in SNC Redis Bundle's configuration:

`->scalarNode('doctrine_cache_predis')->defaultValue('Doctrine\Common\Cache\PredisCache')->end()`

A PredisCache is returned. If you look at the documentation for https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/PredisCache.php, none of it's methods are public, and there's no way to retrieve the client: in short, there's no way to interact with the defined cache when retrieving the cache context via the entity manager.

**Comment by curry684** [comment]
Ok, but that class resides in `doctrine/cache`, so what are we to do about it here?

**Comment by curry684** [comment]
Yes, that would be an unacceptable maintenance burden and an awful design choice from the reusable bundle perspective.

Nobody's stopping you from doing it in your application though, that's exactly why you can override the config setting for `doctrine_cache_predis`.
