### ISSUE TITLE
Symfony 4 setup instructions (framework.yaml)

### ISSUE THREAD

**Issue by tommym9** [snc/SncRedisBundle#459]
Hi,

In: https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md there are instructions for setting up the config for this bundle as well as instructions for editing config.yml, however there aren't instructions on how to update framework.yaml for Symfony 4.

I tried the following:

```
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        app: snc_redis.default
```

However I got the following exception:

```
Argument 1 passed to Symfony\Component\Cache\Adapter\TraceableAdapter::__construct() must implement interface Symfony\Component\Cache\Adapter\AdapterInterface, instance of Predis\Client given
```

I presumed I could plug this into framework.yaml, but this doesn't look like its the case. Is this possible, or is the bundle designed to be used more ad-hoc?

Any help would be much appreciated here. 

Cheers

Tom

**Comment by m2payco** [comment]
```
    cache:
        app: cache.adapter.redis
        default_redis_provider: snc_redis.default
```

**Comment by tommym9** [comment]
Thanks @m2payco I'm an idiot.

**Comment by B-Galati** [comment]
@tommym9 You're not.
The Symfony doc for this part is quite obscure :/
