### ISSUE TITLE
2.1.8 does not show on packagist.org

### ISSUE THREAD

**Issue by DamienHarper** [snc/SncRedisBundle#496]
Having `"snc/redis-bundle": "^2.1"` in my `composer.json`, I can't update to version `2.1.8` with `composer update` (it remains on `2.1.7`)

**Comment by curry684** [comment]
Uh that's weird. @B-Galati and I do not have permissions to review the settings on GitHub nor Packagist so I'll have to call in others here. @snc or @Seldaek have any idea why this release wasn't picked up yet after 2 days?

**Comment by B-Galati** [comment]
@DamienHarper Thanks a lot for reporting this!

Could be related to https://twitter.com/packagist/status/1037035587453235201

**Comment by curry684** [comment]
That would be for @snc to investigate.

**Comment by cloakedninjas** [comment]
Have been having issues with the whole `phpredis` and lazy loading issue and 2.1.8 release addresses these. For anyone else wanting this version, you can add an entry into `composer.json`:

```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/snc/SncRedisBundle"
     }
]
```

And then `composer require snc/redis-bundle "^2.1.8"`

**Comment by Seldaek** [comment]
@curry684 seems the package is set to autoupdate correctly - maybe @snc did it in the meantime - and the 2.1.8 is available.

**Comment by B-Galati** [comment]
@Seldaek Yes he did! Thank you all!
