### ISSUE TITLE
ClientLocatorPass::createClientLocatorDefinition : add definition without id.

### ISSUE THREAD

**Issue by ochi51** [snc/SncRedisBundle#520]
Symfony version: 4.3.1
SncRedisBundle: master

https://github.com/snc/SncRedisBundle/blob/master/DependencyInjection/Compiler/ClientLocatorPass.php#L99

`$container->addDefinitions([$clientLocatorDefinition]);` of 
`\Snc\RedisBundle\DependencyInjection\Compiler\ClientLocatorPass::createClientLocatorDefinition` is set service definition of `int(0)` id.

Please set string id.
Other bundles are based on the assumption that id is string type.

**Comment by stloyd** [comment]
In fact this is bug not enhancement. Which is fixed in #529.

**Comment by B-Galati** [comment]
fixed in #535
