### ISSUE TITLE
Deprecation in RedisBaseCommand, progress on v3?

### ISSUE THREAD

**Issue by linaori** [snc/SncRedisBundle#522]
Fixing deprecations for my Symfony 4.3 upgrade (and yes, I do care about vendor deprecations), I came across this particular deprecation and #484. Now compatibility with 2.0 is achievable by directly injecting what you need as command as a service is possible in 2.x. Now that 2.x is no longer maintained though, I don't see this as an obstacle regardless. 

In #433 this deprecation was fixed, but only present in the master. For the master there seems to be a release called `3.0.0-RC2`, but was released on Feb 20, which is roughly 5 months ago. What's the progress on v3? Will it be released soon? Are there still things that need fixing first?

**Comment by B-Galati** [comment]
It's going to be released soonish, see #452 

I did not take the time to do it yet.

**Comment by B-Galati** [comment]
Coming weeks

**Comment by linaori** [comment]
Thanks for the update!
