### ISSUE TITLE
Error on deprecation message

### ISSUE THREAD

**Issue by HitoTech** [snc/SncRedisBundle#523]
Hello,

I updated my project with the version 2.1.10, and I've seen that there is a deprecation on the bundle service name.
But it seems that the message in the logs is incorrect, because the same service name appears twice :

`[2019-07-30 10:28:41] php.INFO: "snc_redis.front" service is deprecated since 2.1.10, to be removed in 3.0. Please use "snc_redis.front" instead.`

The error seems to come from SncRedisExtension.php in line 307.

Am I the only one having this error ?

**Comment by B-Galati** [comment]
Thanks for reporting! You are right, I have the same thing.

PR welcome if you want to give it a try ;-)

**Comment by HitoTech** [comment]
Never done it on Github, but I will try later :)

**Comment by B-Galati** [comment]
Just implemented one at #524

Let me know if it works for you.

You can send a new PR if you have a better alternative! Will take it with great pleasure.

**Comment by HitoTech** [comment]
Well, I was trying to do it, but you were faster than me 😅

I made a comment on your PR, I don't think I need to make one now.

**Comment by B-Galati** [comment]
Fixed in 2.1.11
