### ISSUE TITLE
Phpredis factory adds wrong parameter for non-persistent connections

### ISSUE THREAD

**Issue by starred-gijs** [snc/SncRedisBundle#537]
The `PhpredisClientFactory` does an incorrect check at line https://github.com/snc/SncRedisBundle/blob/86b5d1e4a82701bb172800106bb1c719a03bb1bd/Factory/PhpredisClientFactory.php#L58

If the value is `false`, the condition is true, see this screenshot, and adds an extra parameter to the call, the "PersistentId", which does not make sense.

![Screenshot 2019-10-08 at 17 00 02](https://user-images.githubusercontent.com/42832118/66407442-80dd0480-e9ed-11e9-8323-fc9aa2ddb663.png)

**Comment by B-Galati** [comment]
@starred-gijs You are god damn right!
