### ISSUE TITLE
Secure connection via phpredis doesn't work

### ISSUE THREAD

**Issue by benburleson** [snc/SncRedisBundle#562]
I use PHPRedis (not Predis) and recently started upgrading our Redis instances to enable encryption in transit, but found that connections via snc wouldn't work. After some debugging, I found that snc's phpredis factory didn't care if the secure protocol `rediss` was used in the dsn config.

I found that changing this line https://github.com/snc/SncRedisBundle/blob/master/Factory/PhpredisClientFactory.php#L138 to the following allows secure connections via PHPRedis:

```
$connectParameters[] = ($parsedDsn->getTls() ? 'tls://' : '') . $parsedDsn->getHost();
```

After this change, I can switch between the old (not encrypted) and new (encrypted) instances just by changing the dsn config for snc_redis.

**Comment by B-Galati** [comment]
Thanks, could you send a PR please? With tests and doc updated, etc.

**Comment by benburleson** [comment]
Hi @B-Galati , do you have any notes for contributing, specifically for running the tests? It's not obvious what I would need set up locally, if anything.

**Comment by B-Galati** [comment]
@benburleson You would need to run a redis instance like so: `docker run --rm -it -p 6379:6379 redis:4`

**Comment by curry684** [comment]
We fixed this in 2.x with https://github.com/snc/SncRedisBundle/pull/445, was it not properly forward ported to 3.x at the time?

**Comment by B-Galati** [comment]
> We fixed this in 2.x with #445, was it not properly forward ported to 3.x at the time?

I think it was only for Predis not PHPRedis
