### ISSUE TITLE
Prefixing with Predis

### ISSUE THREAD

**Issue by DemigodCode** [snc/SncRedisBundle#574]
Cause Predis removed the PrefixableCommandInterface, the Prefixing is not working anymore with all commands.

When symfony cache:pool:clear tries to clear the cache, the scan call doesn't find ANY keys to delete.
The KeyPrefixProcessor of Predis now just adds the prefix at start of the command instead of on start of the key.

There has to be a CommandCallbackHandler registered on the KeyPrefixProcessor for those commands like "scan", which prefixes the correct value in the command arguments of the command being executed.

**Comment by curry684** [comment]
Given that Predis has been abandoned for over 3 years I would recommend just switching to phpredis (see the note in our README as well). We're not actively maintaining compatibility with it anymore, it's just more or less there 'as is, no guarantees anymore'.

**Comment by curry684** [comment]
See https://github.com/snc/SncRedisBundle/issues/589#issuecomment-680879982

I don't see an issue on our end here so I'm closing this issue.
