### ISSUE TITLE
Lazy config is not working with phpredis.

### ISSUE THREAD

**Issue by Basster** [snc/SncRedisBundle#578]
I've noticed that a lazy config with phpredis and doctrine still requires a connection to the server, otherwise it fails:

I ran a `bin/console cache:clear` in my Dockerfile and noticed this bug.

The `snc_redis.<name>` services are lazy, but the `\Snc\RedisBundle\DependencyInjection\SncRedisExtension::loadDoctrine` provides this `$definitionFunction`:

```php
case 'phpredis':
    $definitionFunction = function ($client, $cache) use ($container) {
    $def = new Definition($container->getParameter('snc_redis.doctrine_cache_phpredis.class'));
    $def->addMethodCall('setRedis', array($client));
    if ($cache['namespace']) {
      $def->addMethodCall('setNamespace', array($cache['namespace']));
    }
    return $def;
  };
  break;
```
Seems okay and somehow "lazy", but once the actual `\Doctrine\Common\Cache\RedisCache::setRedis` call is made (e.g. during container warmup) it calls `$redis->setOption(Redis::OPT_SERIALIZER, $this->getSerializerValue());` on the proxy which will be instantiated immediately, which calls `\Snc\RedisBundle\Factory\PhpredisClientFactory::createClient` which includes this:

```php
if (!empty($options['connection_persistent'])) {
 $client->pconnect(...$connectParameters);
} else {
 $client->connect(...$connectParameters);
}
```
...but there is no connection. :(

I'll provide a pull request with a solution in a few minutes.

Hotfix in my app: Manually tagging all `doctrine.orm.**_cache` definitions lazy in a CompilerPass.

**Comment by B-Galati** [comment]
Hello!

Try not to use the doctrine config from this bundle and instead configure things explictly like described in https://github.com/snc/SncRedisBundle/issues/554#issuecomment-563891369.

It should fix your issue.

**Comment by Basster** [comment]
thx @B-Galati, that fixed it, so maybe my PR is obsolete (even though it fixes it, as well :wink:)

**Comment by B-Galati** [comment]
@curry684 Don't what you think but on my end I think we should deprecate and then the doctrine integration. I can try to do it ASAP if you are ok.

**Comment by curry684** [comment]
Yes, that makes sense 👍
