### ISSUE TITLE
Add support for phpredis sentinel

### ISSUE THREAD

**Issue by w1nsun** [snc/SncRedisBundle#584]
phpredis starting from 5.2.0 (https://pecl.php.net/package/redis/5.2.0) supports RedisSentinel

https://github.com/phpredis/phpredis/blob/develop/sentinel.markdown#readme

**Comment by B-Galati** [comment]
@w1nsun Hey! no plan for now. 

Thanks for your contribution, this feature request is now tracked.

Feel free to try to implement it.

**Comment by tarjei** [comment]
What is needed apart from passing the right parameters to the Connection class?

**Comment by OxCom** [comment]
2 years passed. any updates?

**Comment by ostrolucky** [comment]
No interest from my side because I don't use sentinel myself. PR needs to come from somebody who needs it.

**Comment by ostrolucky** [comment]
Needed it myself now, so good news: It's supported now since [4.4.0](https://github.com/snc/SncRedisBundle/releases/tag/4.4.0) :)
