### ISSUE TITLE
Update README in regards to Predis

### ISSUE THREAD

**Issue by nrk** [snc/SncRedisBundle#589]
From the current README:

> As Predis has not been maintained since 2016 it is highly recommended to use the faster and native phpredis extension instead.

Well just to let you know that this should be updated now as Predis is back from the grave :wink: I purposely chose to avoid a pull request and let you handle the phrasing in a way that suits recommendations for this bundle.

**Comment by curry684** [comment]
Welcome back to the land of the living  😉   It's not as simple as just removing the note though, as code on our end for integrating with Predis has been unmaintained since 2016 as well in practice.

@B-Galati what should we do with this? We started 'deviating' from dual support towards 3.x due to Predis' unmaintained status, and right now I'm not even sure the Predis bindings are reliable or even usable in most recent versions. I even highly doubt anyone at all is using Predis with one of our maintained versions.

**Comment by curry684** [comment]
#574 and #566 spring to mind in relation to this.

**Comment by B-Galati** [comment]
>I even highly doubt anyone at all is using Predis with one of our maintained versions.

I don't know either ^^
Based on some issues we can be sure that Predis is still used but that's all we know.
Also, our tests are using Predis a lot so the configuration should be okish somehow.
We'll see what issues are coming along the way.

I think we can now continue to support Predis. In practice we should not have dropped anything from what we had in 2016.
So updating the note should be ok. (I may be wrong as I am quite new in the project lifecycle).

**Comment by curry684** [comment]
> I may be wrong as I am quite new in the project lifecycle

2 weeks after me and I'm afraid it's up to us   😉 

How about I replace the note with a generic note stating Predis support "may be outdated" or something like that?

**Comment by nrk** [comment]
> Welcome back to the land of the living 😉 It's not as simple as just removing the note though, as code on our end for integrating with Predis has been unmaintained since 2016 as well in practice.

@curry684 thanks 😄 And no worries, that's why I remained vague and just wrote "update" instead "remove" for that note 👍 

> #574 and #566 spring to mind in relation to this.

About #574 I'm not even sure what the user is describing as `Predis\Command\PrefixableCommandInterface` has never been removed from the current stable release of Predis and actually it's still present in `v2.0-dev` (main branch). Aside from that, I can't find [any trace of `SCAN` being used by this bundle](https://github.com/snc/SncRedisBundle/search?q=scan&unscoped_q=scan) so I wonder why that issue has been created here to begin with.

**Comment by B-Galati** [comment]
@curry684 

> How about I replace the note with a generic note stating Predis support "may be outdated" or something like that?

I would prefer something like: "Predis is active again since august 2020 and thus it can be a safe choice. However PhpRedis extension is still recommended whenever it's possible as its integration with the bundle is more battle tested for now."

**Comment by curry684** [comment]
@nrk happy with https://github.com/snc/SncRedisBundle/commit/78b6d68701f97e1eb4d33a928936a3e4d95e791f?

**Comment by nrk** [comment]
> @nrk happy with [78b6d68](https://github.com/snc/SncRedisBundle/commit/78b6d68701f97e1eb4d33a928936a3e4d95e791f)?

Thanks 👍

**Comment by curry684** [comment]
Awesome 💯

**Comment by B-Galati** [comment]
Thanks @curry684 🙏
