### ISSUE TITLE
How to force reconnection on redis timeout?

### ISSUE THREAD

**Issue by Webonaute** [snc/SncRedisBundle#595]
We are using swoole with hundreds of workers, sometime when workers are idling for too long, redis go away. than a request come and redis do not reconnect to DB. It just throw error on GET method. So how we can keep alive the connection or force the service to reconnect?

**Comment by patie** [comment]
@Webonaute hi, we resolving same problem, have you reasonable solutions for this? thank you!

**Comment by tourze** [comment]
Same problem, any one have solved this?
