### ISSUE TITLE
Hi. snc_redis removed after composer update

### ISSUE THREAD

**Issue by andrconstruction** [snc/SncRedisBundle#597]
Thanks for this bundle. I faced with next problem. When I make a composer update or some other actions, composer remove the snc/redis-bundle, I cant understand why, can you advise something?

**Comment by xabbuh** [comment]
Can you show your `composer.json` file?

**Comment by andrconstruction** [comment]
[composer - Copy.txt](https://github.com/snc/SncRedisBundle/files/5512966/composer.-.Copy.txt)

**Comment by xabbuh** [comment]
Well, you did not require this bundle in your `composer.json` file. If you change that, it should be kept.

**Comment by andrconstruction** [comment]
> Well, you did not require this bundle in your `composer.json` file. If you change that, it should be kept.

Becouse it was already removed by composer

**Comment by andrconstruction** [comment]
Symfony operations: 1 recipe (640d83830807ae55a5777a672232cbdf)
   - Configuring snc/redis-bundle (>=2.0): From github.com/symfony/recipes-contrib:master
 Executing script cache:clear [KO]
  [KO]
 Script cache:clear returned with error code 1
 !!  
 !!  In ClientLocatorPass.php line 53:
 !!                                                         
 !!    no redis clients found (tag name: snc_redis.client)  
 !!                                                         
 !!  
 !!  
 Script @auto-scripts was called via post-update-cmd

**Comment by andrconstruction** [comment]
On my dev machine I have no a redis lib. And then I got a new error 
 Executing script cache:clear [KO]
  [KO]
 Script cache:clear returned with error code 255
 !!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#7333
 !!    #message: """
 !!      Attempted to load class "Redis" from the global namespace.\n
 !!      Did you forget a "use" statement?

**Comment by andrconstruction** [comment]
Next I installed the redis extenstion, have a next error

 Executing script cache:clear [KO]
  [KO]
 Script cache:clear returned with error code 1
 !!  
 !!  In PhpredisClientFactory.php line 155:
 !!                                                                                 
 !!    No connection could be made because the target machine actively refused it.  
 !!                                                                                 
 !!  
 !!  
 Script @auto-scripts was called via post-update-cmd

Why  need it on a dev machine?

**Comment by andrconstruction** [comment]
So many errors for a install that bandle. I think it should handled during install

**Comment by curry684** [comment]
> Becouse it was already removed by composer

Composer doesn't do that unless you explicitly ask it to. Most likely one of your other dependencies removed this bundle as a hard dependency and thus it got removed. You can check this by reverting to your old `composer.json` and using `composer why snc/redis-bundle`, it will shows you the recursive reason for installing it.

As for the other issues, they're all on your end - you're missing the `phpredis` extension, and `cache:clear` obviously fails until you have configured the bundle.

Closing this issue as there is nothing here related to the bundle.
