### ISSUE TITLE
TLS - Certificate verify failed

### ISSUE THREAD

**Issue by Miloud-H** [snc/SncRedisBundle#598]
Hi,

I'm trying to use TLS with SncRedis, I configured my redis server to use a ca.crt file, server cert and server key.

After changing my dsn to 'rediss://password@localhost' i have this error :

Warning: Redis::connect(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

To check the validity of the certificate I tried the 'openssl verify -verbose -CAfile /path/to/ca/ca.crt /path/to/cert/dev.crt ' and it worked.

Can we pass a ca cert in the config to fix this ?

**Comment by B-Galati** [comment]
Hello,
I have no idea. I think you should add the root certificate in your machine certificates lists.
