### ISSUE TITLE
BC break with SncRedisBundle >=4.0 when calling multi()

### ISSUE THREAD

**Issue by noofaq** [snc/SncRedisBundle#640]
I had code which was working just fine with SncRedisBundle 3.* branch:
```
        $redis = $this->redisClient->multi();
        foreach ($items as $item) {
            $redis->zAdd(self::QUEUE_KEY, $item->getAuditDefinitionId(), $this->serialize($item));
        }
        $result = $redis->exec();
```

After upgrading to 4.0 it started to cause multiple errors in tests:
![obraz](https://user-images.githubusercontent.com/1412384/146041951-0f3768c7-080c-4014-9940-1aaf4f505031.png)
NOTE; the offending line 31 is the one which starts multi transaction

This can be solved by setting mode value manually when calling `multi`:
```
        $redis = $this->redisClient->multi(\Redis::MULTI);
        foreach ($items as $item) {
            $redis->zAdd(self::QUEUE_KEY, $item->getAuditDefinitionId(), $this->serialize($item));
        }
        $result = $redis->exec();
```
NOTE; I am explicitly using value which is supposed to be used by default according to phpredis documentation

When I lock this bundle to version below <4.0 everything runs as before.

# Configuration details:

PHP version:
![obraz](https://user-images.githubusercontent.com/1412384/146042975-8a641bad-1d33-41bb-9092-974d9dc5dd97.png)

PHP Redis extension:
![obraz](https://user-images.githubusercontent.com/1412384/146042938-a351efec-c190-4562-98cc-5c6861f28cc2.png)

Bundle configuration in Symfony:
![obraz](https://user-images.githubusercontent.com/1412384/146043437-8a26622c-3205-4ecb-8985-3ec01d51acf3.png)

Symfony version: `5.4.1`

**Comment by ostrolucky** [comment]
I've created https://github.com/phpredis/phpredis/issues/2044 as issue should be solved there.
