### ISSUE TITLE
Redis warning when using rawCommand with logging enabled

### ISSUE THREAD

**Issue by alexsegura** [snc/SncRedisBundle#647]
When logging is enabled, using the `rawCommand` with phpredis triggers a warning. 

It is because when running for example `SCAN fleet CURSOR 0 LIMIT 10`, the proxied instances gets passed a structure like this :

```
Array
(
    [0] => SCAN
    [1] => Array
        (
            [0] => fleet
            [1] => CURSOR
            [2] => 0
            [3] => LIMIT
            [4] => 10
        )

)
```

The 2nd argument is an array, thus triggering the "not scalar" warning. In this case it should be a flat array containing all the arguments of the initial method call. 

<img width="1059" alt="Capture d’écran 2022-01-25 à 01 49 28" src="https://user-images.githubusercontent.com/1162230/150892664-1adc2933-b006-4dac-b8c3-bae5068e547d.png">

**Comment by ostrolucky** [comment]
Fix is probably as easy as adding $args['args'] to the $otherMembers fix, like was done at https://github.com/snc/SncRedisBundle/commit/341ea72b9ef4fc85ea80bdebbefb7ed8de6e6bea. Can you try that and create a PR (including adding the call in PhpredisClientFactoryTest.php)?

**Comment by alexsegura** [comment]
@ostrolucky yes, I had a similar fix. I will submit a PR 🙂

**Comment by alexsegura** [comment]
@ostrolucky I have looked at the code and IMHO it looks complicated to add a fix for each and every parameter. 

From what I understand it takes the parameters from [redis.stub.php](https://github.com/phpredis/phpredis/blob/56633e1b6b07e5824ba3f4b4c15a90ee3b7f0e1e/redis.stub.php)? Would you be against using reflection to check if the parameter is variadic?

**Comment by ostrolucky** [comment]
I would stick to current blacklist for now. Performance is important especially for something like redis and reflection is slow

**Comment by alexsegura** [comment]
@ostrolucky thank you for accepting my pull request 🙂 

Would you be so kind and make a new release, please? Thanks!

**Comment by ostrolucky** [comment]
released
