### ISSUE TITLE
Symfony cache warmup on pipline 

### ISSUE THREAD

**Issue by wirwolf** [snc/SncRedisBundle#655]
Hello. I deploy my application using docker container and I want to warmup cache on the pipeline. 
But when I run  ``` /app/bin/console -vvv cache:warmup``` in pipeline i see connect error, because connect to Redis instance  create in https://github.com/snc/SncRedisBundle/blob/master/src/Factory/PhpredisClientFactory.php#L146

Please, could you change the logic of your service to the following: create a connection only when application request some data

**Comment by ostrolucky** [comment]
Maybe you are saving metadata in redis? Those are needed during warmup. Also, have you installed friendsofphp/proxy-manager-lts?

**Comment by wirwolf** [comment]
No, i not use friendsofphp/proxy-manager-lts.
Yes, one of connections is used for synfony cache

**Comment by ostrolucky** [comment]
If redis is configured for doctrine metadata, then redis has to be available during the build, I don't see a way around that, sorry.

**Comment by wirwolf** [comment]
@ostrolucky fix this issue is simple. Remove the connection to Redis from PhpredisClientFactory->createClient, and connect to Redis server on demand when the user accesses(get key, or set key or exist key end other) the Redis service

**Comment by ostrolucky** [comment]
This should be already working, you just need to install friendsofphp/proxy-manager-lts, this is it's job. See https://github.com/snc/SncRedisBundle/tree/master/docs#troubleshooting
