### ISSUE TITLE
Add support for username in phpredis ACL authentication

### ISSUE THREAD

**Issue by succoDiPompelmo** [snc/SncRedisBundle#657]
Hi,

I'm trying to upgrade my PHP cluster with Redis 6.0 and ACL configured but it doesn't seems to be an username config to define in the snc_redis.yaml for phpredis, only password, is this correct ? There is a way to enable the use of username and password for authenticate with ACL Redis ?

**Comment by succoDiPompelmo** [comment]
Right now I'm using phpredis and on their doc is present this par ton authentication with username/password 
```php
/* Authenticate with the password 'foobared' */
$redis->auth('foobared');

/* Authenticate with the username 'phpredis', and password 'haxx00r' */
$redis->auth(['phpredis', 'haxx00r']);
```

**Comment by succoDiPompelmo** [comment]
Ok, I will try. Thank you.

**Comment by ostrolucky** [comment]
Solved in https://github.com/snc/SncRedisBundle/pull/660
