### ISSUE TITLE
The current version is not working with predis 2.0

### ISSUE THREAD

**Issue by opillion** [snc/SncRedisBundle#666]
Hi I upgraded to predis 2.0 and got this error on composer install:

`Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#3394
!!    #message: """
!!      Attempted to load class "Factory" from namespace "Predis\Profile".\n
!!      Did you forget a "use" statement for e.g. "Predis\Connection\Factory", "Predis\Command\Factory", "Faker\Factory" or "Doctrine\DBAL\Driver\IBMDB2\Exception\Factory"?
!!      """
!!    #code: 0
!!    #file: "./vendor/snc/redis-bundle/src/DependencyInjection/SncRedisExtension.php"
!!    #line: 170
!!    trace: {
!!      ./vendor/snc/redis-bundle/src/DependencyInjection/SncRedisExtension.php:170 { …}
!!      ./vendor/snc/redis-bundle/src/DependencyInjection/SncRedisExtension.php:117 { …}
!!      ./vendor/snc/redis-bundle/src/DependencyInjection/SncRedisExtension.php:68 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:42 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:716 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:538 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:767 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:128 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:166 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:72 { …}
!!      ./vendor/symfony/console/Application.php:171 { …}
!!      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
!!      ./vendor/autoload_runtime.php:29 { …}
!!      ./bin/console:11 {
!!        ›
!!        › require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
!!        ›
!!        arguments: {
!!          "/var/www/vendor/autoload_runtime.php"
!!        }
!!      }
!!    }
!!  }
!!  [09-Jun-2022 08:50:38 UTC] 2022-06-09T08:50:38+00:00 [critical] Uncaught Error: Class "Predis\Profile\Factory" not found`

**Comment by opillion** [comment]
someone reported it before  - sorry

**Comment by KalanaPerera** [comment]
what was the solutiion

**Comment by ostrolucky** [comment]
See https://github.com/snc/SncRedisBundle/issues/664
