### ISSUE TITLE
Can't connect using username and password in a DSN

### ISSUE THREAD

**Issue by bruno-buiret** [snc/SncRedisBundle#673]
Hello,

I've been trying to connect to a Redis server using a full DSN `redis://username:password@host:port/database` but there appears to be a problem detecting the username inside the `PhpredisClientFactory` class in the method `createClient()`

```php
$username = $options['parameters']['username'] ?? null;
// Shouldn't this be $dsn->getUsername() ?? $options['parameters']['username'] ?? null; just like for the password?
$password = $dsn->getPassword() ?? $options['parameters']['password'] ?? null;
if ($username !== null && $password !== null) {
    $client->auth([$username, $password]);
} elseif ($password !== null) {
    $client->auth($password);
}
```

For now I've used environment variable processors (https://symfony.com/doc/current/configuration/env_var_processors.html#built-in-environment-variable-processors) to extract the username from the DSN and use the options.parameters.username property.

Thank you!

**Comment by ostrolucky** [comment]
Sorry but it works and is proven to work by this testcase https://github.com/snc/SncRedisBundle/blob/5ac15ab0824a4a4448ba27edd2e2773c159c373d/tests/Factory/PhpredisClientFactoryTest.php#L255-L255 so issue must be somewhere else
