### ISSUE TITLE
SncRedis 3.6 session lock with doctrine cache

### ISSUE THREAD

**Issue by max4ever** [snc/SncRedisBundle#676]
Hi,
I've tried to migrate from `predis` to `phpredis 5` and found a bug that was causing session locks.
I know I'm using not the latest version, but still this might help someone in the future.

The transition is not that simple.

This line is only executed when using `phpredis` and it serializes the token https://github.com/snc/SncRedisBundle/blob/3.6.0/Session/Storage/Handler/RedisSessionHandler.php#L255
just before trying to remove the lock. Meanwhile `predis` does NOT do this step.

The token is always written unserialized https://github.com/snc/SncRedisBundle/blob/3.6.0/Session/Storage/Handler/RedisSessionHandler.php#L204, so in my case when I share the `snc_redis` connection with some class that extends `RedisCache` I have problems.
Doctrine changes the serializer during runtime https://github.com/doctrine/cache/blob/1.13.x/lib/Doctrine/Common/Cache/RedisCache.php#L36
and so then when `snc_redis` tries to unlock it will compare for example the key `s:3"abc"` against `abc` and fail and wait and fail and wait...

I don' t know if you are considering doing a 3.7 version, I think the easiest fix would to just drop that line that encodes the token [at 255](https://github.com/snc/SncRedisBundle/blob/3.6.0/Session/Storage/Handler/RedisSessionHandler.php#L255).

As for me, my fix was to create a new `snc_redis` client under `
snc_redis:
    clients:
        ....
` and then pass that client only to `RedisCache`

Best regards

**Comment by ostrolucky** [comment]
Thanks. But as you mentioned you are not using the latest version and we did remove this handler from there, so there isn't anything to fix on our side actually. Let's close then, this topic should still be discoverable by search.
