### ISSUE TITLE
RedisDsn enhancement

### ISSUE THREAD

**Issue by astronom** [snc/SncRedisBundle#700]
Seems it is not convenient to additionally add e.g `options.replication: sentinel, options.service: mymaster` for sentinel connection instead of recognize a parameter in DSN e.g `?redis_sentinel=mymaster` as it done in Symfony Redis adapter. 

This option can make dev and prod config more clear, because I'm not using Sentinel directly in my code, and can only change DSN env for connection

**Comment by ostrolucky** [comment]
This is not possible with current design unfortunately, because we need to know replication mode at compile time. If someone wants to invest time in reworking this though, PR is welcome.
