### ISSUE TITLE
The Proxy for Redis::scan passes the $iterator by value [bug]

### ISSUE THREAD

**Issue by mihai-stancu** [snc/SncRedisBundle#702]
Hello,

`\Redis::scan` takes its first parameter by reference. However the `LazyObject` implementation accidentally passes all arguments by value via argument unpacking.

```
    public function scan(&$i_iterator, $str_pattern = null, $i_count = null)
    {
        if (isset($this->lazyObjectState)) {
            return ($this->lazyObjectState->realInstance ??= ($this->lazyObjectState->initializer)())->scan(...\func_get_args());
        }

        return parent::scan(...\func_get_args());
    }
```

Scan relies on the iterator to traverse all of the memory blocks Redis has allocated. Finding no matching keys in the first block isn't a guarantee that no matching keys will be found in subsequent blocks. Hence this bug hinders functionality.

**Comment by mihai-stancu** [comment]
I think we are, we're on a Symfony 6.2 + PHP 8.2 environment but checking...

Here is the output of my local version checks:
```
# jq '.packages[]|select(.name=="snc/redis-bundle").version' composer.lock 
"4.6.0"

# jq '.packages[]|select(.name=="friendsofphp/proxy-manager-lts").version' composer.lock 
"v1.0.14"

# php -r 'var_dump(phpversion("redis"));'
Command line code:1:
string(5) "5.3.7"

# php -r 'var_dump(phpversion());'
Command line code:1:
string(5) "8.2.5"
```

**Comment by mihai-stancu** [comment]
All of the above look to be latest (stable) releases from their respective maintainers.

**Comment by mihai-stancu** [comment]
Affected methods:
- hscan
- scan
- sscan
- zscan

Since they are the only ones which have pass by ref.

**Comment by ostrolucky** [comment]
sscan works for sure as tests prove it, diff is here https://github.com/snc/SncRedisBundle/commit/34d6e3b8

**Comment by mihai-stancu** [comment]
It may work if the keys you fetch back reside in the first memory block Redis allocates.

**Comment by mihai-stancu** [comment]
You may be right about that, I'll check.

The reason I isolated this problem to SNC Redis is because of the following code:
```
$i = null;
$keys = $this->container->get('snc_redis.default')->scan($i, $pattern);

assert($i === 0); // this fails because $i === null but $i is supposed to be updated by reference
```

**Comment by mihai-stancu** [comment]
@ostrolucky as long as the new `VarExporter\LazyProxyTrait` is available (i.e. on Symfony >6.2) then hardcoding `->setLazy(true)` then the same issue would occur.

The revert wouldn't fix this.

**Comment by ostrolucky** [comment]
Then what do you suggest we do here? I don't think this bundle can do anything about this.

**Comment by mihai-stancu** [comment]
Indeed this doesn't seem within SncBundle's control.

The lazy loading of the underlying framework changed.

I'll post an issue on Symfony to see how pass by ref gets solved & link it back here?

**Comment by nicolas-grekas** [comment]
This should be fixed by https://github.com/symfony/symfony/pull/50086

**Comment by nicolas-grekas** [comment]
See also https://github.com/symfony/symfony/issues/49959 BTW

**Comment by mihai-stancu** [comment]
Thank you!
