### ISSUE TITLE
DSN with empty username not connecting

### ISSUE THREAD

**Issue by coryhw** [snc/SncRedisBundle#703]
When working with a DSN with the form
rediss://:password@domain:20339

I get a WRONGPASS invalid username-password pair or user is disabled.

![image](https://github.com/snc/SncRedisBundle/assets/6216547/84710b1c-923c-4b00-a360-8020f347445f)

![image](https://github.com/snc/SncRedisBundle/assets/6216547/c6b6338a-19f0-4f13-9407-ef40d563f45e)

In this case the $username variable is being set to an empty string "" so it is calling the two parameter version of $client->auth.  It seems that form gives the above error if the $username parameter is an empty string.

If I force the code to call the single parameter version that only submits the password it works successfully.

One solution could be updating the code to something like this:

![image](https://github.com/snc/SncRedisBundle/assets/6216547/ebe9a201-e477-474b-85d3-7c176b380731)

I can confirm that works in my use case at least.

Thanks!

**Comment by ostrolucky** [comment]
Syntax you should use is  `rediss://password@domain:20339`. This is because normally there is no username as you know.
