### ISSUE TITLE
Monolog proxy breaks PHPRedis SSL integration

### ISSUE THREAD

**Issue by Craige** [snc/SncRedisBundle#708]
When using PHPRedis with SSL and `stream` options, using the Monolog proxy breaks the ability to pass stream options to `Redis#connect()`. Disabling the Monolog proxy and using the direct method call fixes this. I believe this may be due to the proxy using reflection to get `connect()` parameters, which the definition in the extension are:

https://github.com/phpredis/phpredis/blob/5.3.7/redis.c#L113C1-L118C20

Note that this does not include the full definition, which is reflected here:

https://github.com/phpredis/phpredis/blob/5.3.7/redis.c#L1055-L1059

As a result, we wind up with a proxy method like the following that does not forward along the stream/ssl_context when it's set:

<img width="1657" alt="Screen Shot 2023-07-12 at 10 34 45" src="https://github.com/snc/SncRedisBundle/assets/469311/01c7c161-66e8-4168-bb26-b8da161c7680">

And so, if you are setting `ssl_context` in your config, it will not be used if you are using Monolog to log the Redis calls.

**Comment by ostrolucky** [comment]
As you mentioned we rely on reflection. If reflection output we are getting from extension is not correct, we can't do anything. Specifically we don't want to put workarounds here in a bundle, but have reflection fixed. You should raise an issue in phpredis. I've raised similar ones in the past, such as https://github.com/phpredis/phpredis/issues/2044. But you look to be  quite capable here to be able to raise such issue as well over there.

It would be also worth trying out develop branch of phpredis in your case, they did lot of reflection fixes there and we test sncredis with it as well.
