### ISSUE TITLE
snc/redis-bundle": "1.1.10" issues balancing the load between Primary Endpoint & Reader Endpoint

### ISSUE THREAD

**Issue by SebastianUrbanoL** [snc/SncRedisBundle#711]
This is our configuration in a legacy project, where we are facing issues related to the connections to Redis, We increased the capacity of our Redis clusters, but the issue is not related to their capacity, it is related to the way the traffic is balanced, we found some fixes but looks like they are for upper versions, I think this version has an issue balancing the reader operations, this is our actual configuration:

snc_redis:
    clients:
        trfx_core:
            type: predis
            alias: default
            dsn: '%redis_dns%'
            logging: '%kernel.debug%'
            options:
                replication: true
                prefix: '%redis_prefix%'
                connection_timeout: 1
                read_write_timeout: 1
                connection_persistent: true
                cluster: Snc\RedisBundle\Client\Predis\Connection\PredisCluster

and our redis dns config, something like:

redis_dns:
    - 'redis://server_master(PrimaryEndpoint):6379/11?alias=master'
    - 'redis://server_slave1(ReadersEndpoint):6379/11'

However, you can see in the images below that there is a big difference between the traffic that is received by the master compared to the traffic received by the readers 

![image](https://github.com/snc/SncRedisBundle/assets/90208925/9425d156-9c9c-4e1f-80ae-c57ad7ec8f01)
![image](https://github.com/snc/SncRedisBundle/assets/90208925/5a3a61d3-c740-432b-9540-4fb698d117b2)
![image](https://github.com/snc/SncRedisBundle/assets/90208925/5b33f5e0-6ff2-490f-9bb1-a1ca1bf91de3)
![image](https://github.com/snc/SncRedisBundle/assets/90208925/ed9eb76d-05de-4b99-afda-e84da4a33bd7)

We are using Symfony 2.8 for the old project we can't update to a new Symfony version due to some architectural issues, Could you help us identify this as an issue with the version or do you know what we can try? We are thinking maybe there is a way to separate the write and read connections, in order to put the correct domain for each of them, due to at least AWS Elastic Cache offers the option of the read and primary endpoint

And thank you for your great job, What would become of us if you the people who work in open-source projects didn't exist?

By Sebas 🤖

**Comment by ostrolucky** [comment]
This is a redis client issue, not a bundle. AFAIK it connects always to first host at beginning. You could write some extension that randomizes reds_dsns though.
