### ISSUE TITLE
opcache problem with Stopwatch

### ISSUE THREAD

**Issue by koekaverna** [snc/SncRedisBundle#719]
Because stopwatch is a dev depenendency class doesn't exists in production I have this error:

> PHP message: PHP Fatal error:  Failed to load class Symfony\Component\Stopwatch\Stopwatch used by typed property Snc\RedisBundle\Logger\RedisCallInterceptor::$stopwatch during preloading in Unknown on line 0

**Comment by ostrolucky** [comment]
Not sure why is PHP crashing here, since property is optional. Can you craft a reproducer?

**Comment by koekaverna** [comment]
Probably this one is the same https://github.com/symfony/symfony/issues/44364

There is a problem with opcache and type hinted class properties in 7.4

**Comment by ostrolucky** [comment]
Yeah. We can't do much in here. You should upgrade your php version.
