### ISSUE TITLE
Proxy class for \Redis generates with null values in Symfony 5.4 and PHP 7.4

### ISSUE THREAD

**Issue by fr0N73ND3r** [snc/SncRedisBundle#720]
Hellow. I am currently working on a project using Symfony 5.4 and PHP 7.4. I have noticed an issue with the proxy class for \Redis. It seems to be generating with null values where there should be default values.  Here is a brief overview of my setup:  

Symfony version: 5.4
PHP version: 7.4
Redis bundle: snc/redis-bundle version 4.7

The issue can be reproduced in the MainController where I am using the \Redis class. Response is always 0.

See https://github.com/fr0N73ND3r/snc-redis-test/blob/master/src/Controller/MainController.php

Thank you.

**Comment by ostrolucky** [comment]
Unfortunately you will need to update your PHP version for this to work properly https://www.php.net/manual/en/reflectionparameter.getdefaultvalue.php#refsect1-reflectionparameter.getdefaultvalue-changelog

PHP prior to 8.0:
```
php > var_dump((new ReflectionClass('Redis'))->getMethod('incr')->getParameters()[1]->getDefaultValue());

Warning: Uncaught ReflectionException: Cannot determine default value for internal functions in php shell code:1
Stack trace:
#0 php shell code(1): ReflectionParameter->getDefaultValue()
#1 {main}
  thrown in php shell code on line 1
```

after
```
php > var_dump((new ReflectionClass('Redis'))->getMethod('incr')->getParameters()[1]->getDefaultValue());
int(1)
```
