### ISSUE TITLE
Example to cache doctrine query

### ISSUE THREAD

**Issue by ghisleouf** [snc/SncRedisBundle#77]
Hi,

I'm new to Redis and i'm trying to use SncRedisBundle.

Currently, i'm able to to store simple values in Redis (like strings or numbers) but, i'm not able to use Redis to cache some Doctrine queries.

Could you please provide me an example explaining how to store, for example a "findAll()" call into Redis?

I'm also looking for best practices to use Redis as good as possible.

Thanks for your help.

**Comment by unglevan** [comment]
@snc 
i do the same with @ghisleouf 
and check 
1. redis mornitor
they get key `participants `
2. mysql slow log
still query Participant normally

what i'm wrong?
