### ISSUE TITLE
Problems with long running connections

### ISSUE THREAD

**Issue by tarjei** [snc/SncRedisBundle#82]
Hi, I'm using SNC Redis with multiple connections - default is for things I care about, while cache is for things that may die.

Now, my problem is that when I use the default connection (blocking on blpop) together with a second connection for the cache, the cache blows up when blpop returns and I start using the cache since the cache connection has timed out.

Should I use connection_persister:true here or is there another parameter I should use ?

**Comment by JHGitty** [comment]
I think this issue can be closed because it is very old and the issue did not occur again for 2-3 years.
